import {useState} from 'react';
import type {WeeklyDataset,WeeklyPlayer} from '../lib/weekly/types';
export function PlayerResearchCard({player:p}:{player:WeeklyPlayer}){
 const r=p.research;if(!r)return <p>Research evidence is unavailable for {p.name} in this week.</p>;
 return <section className="research-player"><div className="research-player-heading"><div><h4>{p.name}</h4><p>{p.positions.join(' / ')} · {p.team} vs {p.opponent??'TBD'}</p></div><div><strong>{p.mean?.toFixed(1)??'—'}</strong><small>Lineup forecast</small></div><div><strong>{r.candidateMean?.toFixed(1)??'—'}</strong><small>Research model</small></div></div><p className="research-basis">{r.basis}{r.sampleGames!==null?` · ${r.sampleGames} observed games`:''}</p>
 {r.officialStatus&&<p><a href={r.officialStatus.sourceUrl} target="_blank" rel="noreferrer">Official report</a>: {r.officialStatus.status??'Game status not assigned'} · {r.officialStatus.practice??'Practice status unavailable'}{r.officialStatus.injury?` · ${r.officialStatus.injury}`:''}{r.officialStatus.reportedAt?` · reported ${new Date(r.officialStatus.reportedAt).toLocaleString()}`:''}</p>}
 {r.matchup&&<section className="weekly-section"><h4>Estimated WR/CB matchups · {r.matchup.opponent}</h4><p>Low confidence · Personnel observed {new Date(r.matchup.observedAt).toLocaleString()}</p><p>{r.matchup.receiverAlignment}. {r.matchup.shadow}. These groups describe who may cover each alignment; they do not predict how often this receiver faces each defender.</p>{r.matchup.scenarios.map(s=><div key={s.label}><h5>{s.label}</h5><p>{s.explanation}</p>{s.defenders.length?s.defenders.map(d=><div key={d.gsisId??d.name} className="research-model"><strong>{d.name} · {d.position}</strong>{d.performance?<><p>{d.performance.season} regular season · {d.performance.targets} targets across {d.performance.games} games</p><div className="research-signals"><div><span>Yards allowed / target</span><strong>{d.performance.yardsPerTarget.toFixed(2)}</strong></div><div><span>Catch rate allowed</span><strong>{(d.performance.completionRate*100).toFixed(1)}%</strong></div><div><span>Touchdowns allowed</span><strong>{d.performance.touchdowns}</strong></div>{d.performance.lowerYardagePercentile!==null&&<div><span>Lower-yardage percentile</span><strong>{Math.round(d.performance.lowerYardagePercentile)}</strong><small>Higher means fewer yards allowed per target · {d.performance.cohortSize} qualifying corners</small></div>}</div></>:<p>Individual coverage sample unavailable.</p>}</div>):<p>No current depth-chart listing for this alignment.</p>}</div>)}<p>Coverage results reflect opponents, assignments and scheme as well as defender ability. Depth-chart starters can change with injuries and packages. These estimates currently inform the explanation; forecast points stay unchanged.</p><details><summary>Matchup assumptions</summary><ul>{r.matchup.notes.map(n=><li key={n}>{n}</li>)}</ul><a href="https://nflreadr.nflverse.com/reference/load_pfr_advstats.html" target="_blank" rel="noreferrer">PFR coverage data via nflverse</a></details></section>}
 <div className="research-signals">{r.signals.map((s,i)=><div key={i}><span>{s.label}</span><strong>{s.value}</strong>{s.note&&<small>{s.note}</small>}</div>)}</div><ul>{r.notes.slice(0,5).map((n,i)=><li key={i}>{n}</li>)}</ul>{r.notes.length>5&&<details><summary>More evidence</summary><ul>{r.notes.slice(5).map((n,i)=><li key={i}>{n}</li>)}</ul></details>}
 </section>;
}
export function WeeklyResearch({dataset:d,week,rosterIds=[]}:{dataset:WeeklyDataset;week:number;rosterIds?:string[]}){
 const[query,setQuery]=useState('');const[selected,setSelected]=useState('');const research=d.research;
 if(!research)return <section className="weekly-section"><h3>Weekly research</h3><p>The research briefing is being prepared.</p></section>;
 if(research.week!==week)return <section className="weekly-section"><h3>Research follows the current games</h3><p>The latest briefing covers week {research.week}. Select that week for current game conditions and injury reports. Future forecasts remain scenarios.</p></section>;
 const players=d.weeks[week]?.players??{};
 const matches=Object.values(players).filter(p=>p.research&&(query?p.name.toLowerCase().includes(query.toLowerCase()):rosterIds.length?rosterIds.includes(p.id):p.mean!==null)).sort((a,b)=>(b.mean??-1)-(a.mean??-1)).slice(0,query?15:8);
 const player=matches.find(p=>p.id===selected)??matches[0];
 return <section className="weekly-research"><div className="research-heading"><div><p className="eyebrow">THIS WEEK’S RESEARCH</p><h3>Week {week} game briefing</h3></div><p>Built {new Date(research.generatedAt).toLocaleString()}</p></div>{research.sources.some(s=>s.status!=='ok')&&<p role="status">Some research sources are stale or unavailable. Their limits are listed under Research sources and coverage.</p>}<p>Weekly analysis with daily and pregame source refreshes. Your roster updates only when you click Update roster.</p>
 <div className="research-game-grid">{research.games.map(g=><details className="research-game" key={g.gameId}><summary><strong>{g.awayTeam} at {g.homeTeam}</strong><span>{g.kickoff?new Date(g.kickoff).toLocaleString(undefined,{weekday:'short',hour:'numeric',minute:'2-digit'}):'Kickoff unconfirmed'}</span></summary><p>{g.venue} · {g.roof}</p>{g.weather.length?<div className="research-signals">{g.weather.map((s,i)=><div key={i}><span>{s.label}</span><strong>{s.value}</strong>{s.note&&<small>{s.note}</small>}</div>)}</div>:<p>Game weather unavailable.</p>}{g.market.map((m,i)=><p key={i}>{m.label}: {m.value}{m.note?` · ${m.note}`:''}</p>)}{g.notes.map((n,i)=><p key={i}><small>{n}</small></p>)}</details>)}</div>
 <div className="research-model"><h4>Independent forecast check</h4><p>{research.model.summary}</p><details><summary>Measured model results</summary><p>MAE is the average forecast miss in fantasy points. Lower is better. Historical provider forecasts may have been revised after games.</p><div className="research-signals">{Object.entries(research.model.metrics).map(([name,value])=><div key={name}><span>{name.replaceAll('_',' ')}</span><strong>{value.toFixed(3)}</strong></div>)}</div><p>More simulations reduce sampling noise. They do not establish that the forecasts are accurate.</p></details></div>
 <div className="research-player-search"><label htmlFor="research-player">Research a player</label><input id="research-player" type="search" placeholder="Search any player…" value={query} onChange={e=>{setQuery(e.target.value);setSelected('');}}/><div className="research-player-options">{matches.map(p=><button type="button" className="btn" aria-pressed={player?.id===p.id} key={p.id} onClick={()=>setSelected(p.id)}>{p.name}</button>)}</div></div>{player&&<PlayerResearchCard player={player}/>} {!matches.length&&<p>No matching research record.</p>}
 <details className="weekly-section"><summary>What changed since the previous research run?</summary>{research.changes.length?research.changes.map((c,i)=><p key={i}><strong>{c.title}</strong>: {c.detail}</p>):<p>No comparable player changes yet. The first briefing establishes the comparison snapshot.</p>}</details>
 <details className="weekly-section"><summary>Research sources and coverage</summary><p>Weather data by <a href="https://open-meteo.com/" target="_blank" rel="noreferrer">Open-Meteo</a>, used under <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noreferrer">CC BY 4.0</a>.</p><ul>{research.limitations.map((l,i)=><li key={i}>{l}</li>)}</ul><ul className="weekly-sources">{research.sources.map((s,i)=><li key={i}><a href={s.url} target="_blank" rel="noreferrer">{s.name}</a> · {s.status}<small>Collected {new Date(s.fetchedAt).toLocaleString()}{s.note?` · ${s.note}`:''}</small></li>)}</ul></details>
 </section>;
}
