import { MANAGERS } from '../lib/weekly/config';
import type { useWeeklyWorkspace } from '../lib/weekly/workspace';
export function WeeklyControls({workspace:w,selected,onSelect}:{workspace:ReturnType<typeof useWeeklyWorkspace>;selected:string;onSelect:(id:string)=>void}) {
  return <>
    <div className="weekly-controls"><div><span className="weekly-control-label">Whose team?</span><div className="weekly-managers" role="group" aria-label="Manager">{MANAGERS.map(m=><button className="btn" type="button" key={m.userId} aria-pressed={selected===m.userId} onClick={()=>onSelect(m.userId)}>{m.name}</button>)}</div></div><div className="weekly-week-picker"><label>Week <select aria-label="NFL week" value={w.week} onChange={e=>w.setWeek(Number(e.target.value))}>{Array.from({length:18},(_,i)=><option value={i+1} key={i+1}>{i+1}</option>)}</select></label><button type="button" className="btn subtle" onClick={()=>w.setWeek(0)}>This week</button></div></div>
    <section className="weekly-status" aria-label="Roster and forecast status"><div className="weekly-status-main"><div><strong role="status">{w.checking ? 'Getting your players…' : w.error ? 'Your roster needs another try' : w.saved?.snapshot.rosteredPlayers ? 'Your saved roster is ready' : 'Ready when you draft'}</strong><p>{w.saved ? `Last roster update: ${new Date(w.saved.snapshot.checkedAt).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}` : 'Bring your players over from Sleeper to get started.'}</p></div><button type="button" className="btn weekly-primary" disabled={w.checking} onClick={w.updateRoster}>{w.checking?'Updating…':'Update roster'}</button></div><small>Click after drafting, making a trade or adding a player. Updates happen only when you ask.</small>
      {w.error&&<p role="alert">{w.error}. Click Update roster to retry.</p>}
      {w.dataset?.sources.some(s=>s.status==='stale')&&<p className="weekly-status-note">Some forecasts are older. Check the update details before relying on future-week predictions.</p>}
      {w.dataError&&<p role="alert">{w.dataError}</p>}
      <details className="weekly-update-details"><summary>Forecast updates &amp; details</summary><div className="weekly-feed-row"><span>{w.dataset ? `Forecasts updated ${new Date(w.dataset.generatedAt).toLocaleString()}` : w.loading ? 'Loading forecasts…' : 'Forecasts unavailable'}</span><button className="btn subtle" type="button" disabled={w.loading} onClick={w.reloadAnalysis}>Reload forecasts</button></div><p>Forecasts estimate fantasy points. Reloading gets the latest published analysis; Update roster gets your players from Sleeper.</p></details>
    </section>
  </>;
}
