import assert from 'node:assert/strict';
import {build} from 'esbuild';
const compiled = await build({entryPoints:['src/lib/weekly/report.ts'],bundle:true,write:false,format:'esm',platform:'node'});
const {buildLineupReport} = await import(`data:text/javascript;base64,${Buffer.from(compiled.outputFiles[0].text).toString('base64')}`);
const player=(id,mean,positions=['RB'],kickoff=300)=>({id,name:id,mean,positions,kickoff,status:null,availability:'available'});
const players=Object.fromEntries([player('a',10),player('b',15),player('c',13),player('waiver',18),player('owned',25),player('ir',40)].map(p=>[p.id,p]));
const dataset={season:'2026',scoring:{rec:.5},weeks:{1:{players,warnings:[]}},calibration:{residuals:{RB:[-3,0,3]}}};
const snapshot={season:'2026',scoring:{rec:.5},slots:['RB','BN'],rosters:[{rosterId:1,players:['a','b','c','ir'],reserve:['ir'],starterSlots:['a']},{rosterId:2,players:['owned'],reserve:[],starterSlots:['owned']}]};
const input={dataset,snapshot,rosterId:1,week:1,now:100};
const report=buildLineupReport(input);
assert.equal(report.current.assignments[0].playerId,'a');assert.equal(report.recommended.assignments[0].playerId,'b');
assert.equal(report.comparison.expectedGain,5);assert.equal(report.swaps[0].expectedGain,5);
assert.deepEqual(report.waivers.map(row=>row.player.id),['waiver']);assert.equal(report.waivers[0].expectedGain,3);
assert.equal(report.pairwise.sitId,'c');assert.equal(report.contingencies.length,0);
const blank=buildLineupReport({...input,currentStarters:['0']});
assert.equal(blank.current.assignments[0].playerId,null);assert.equal(blank.comparison.expectedGain,null);assert.equal(blank.swaps[0].expectedGain,null);
assert.equal(blank.pairwise.comparison.status,'experimental');
const question=buildLineupReport({...input,dataset:{...dataset,weeks:{1:{players:{...players,b:{...players.b,status:'Questionable'}},warnings:[]}}}});
assert.equal(question.contingencies.length,1);assert.equal(question.contingencies[0].lineup.assignments[0].playerId,'c');
const missing=buildLineupReport({...input,snapshot:{...snapshot,rosters:[{...snapshot.rosters[0],players:[...snapshot.rosters[0].players,'missing']}]}});
assert.equal(missing.recommended.complete,false);assert.equal(missing.comparison.status,'unavailable');assert.ok(missing.warnings.some(warning=>warning.includes('missing')));
const wrong=buildLineupReport({...input,dataset:{...dataset,scoring:{rec:1}}});
assert.equal(wrong.recommended.complete,false);assert.equal(wrong.pairwise,null);assert.equal(wrong.waivers.length,0);
const opponent=buildLineupReport({...input,opponentRosterId:2});assert.ok(opponent.comparison.opponentWin);
const locked=buildLineupReport({...input,now:350});assert.equal(locked.recommended.assignments[0].playerId,'a');assert.equal(locked.comparison.status,'unavailable');assert.equal(locked.waivers.length,0);
const blanks=buildLineupReport({...input,snapshot:{...snapshot,slots:['RB','FLEX','BN']},currentStarters:['0','a']});
assert.equal(blanks.current.assignments[0].playerId,null);assert.equal(blanks.current.assignments[1].playerId,'a');
console.log('weekly report fixtures passed');
