import assert from 'node:assert/strict';
import {build} from 'esbuild';
const compiled = await build({entryPoints:['src/lib/weekly/simulate.ts'],bundle:true,write:false,format:'esm',platform:'node'});
const {compareLineups,createContingencies} = await import(`data:text/javascript;base64,${Buffer.from(compiled.outputFiles[0].text).toString('base64')}`);
const player=(id,mean,kickoff=300)=>({id,name:id,mean,positions:['RB'],availability:'available',kickoff});
const players=Object.fromEntries([player('a',10),player('b',12),player('c',11),player('early',8,200)].map(p=>[p.id,p]));
const lineup=(id,locked=false)=>({assignments:[{index:0,slot:'RB',playerId:id,mean:players[id].mean,locked}],total:players[id].mean,complete:true,issues:[]});
const input={players,baseline:lineup('a'),recommended:lineup('b'),residuals:{RB:[-5,0,5]},seed:7};
assert.equal(compareLineups({...input,residuals:{}}).status,'unavailable');
assert.equal(compareLineups({...input,residuals:{RB:[NaN,2]}}).probabilityImproves,null);
const result=compareLineups(input);
assert.equal(result.draws,20000);assert.equal(result.expectedGain,2);assert.equal(result.status,'experimental');
assert.ok(result.probabilityImproves>.6 && result.probabilityImproves<.72);
assert.deepEqual(compareLineups(input),result);
const same=compareLineups({...input,recommended:input.baseline});
assert.deepEqual(same.gain,{mean:0,median:0,p10:0,p90:0});assert.equal(same.probabilityTies,1);assert.equal(same.probabilityImproves,0);
const opponent=compareLineups({...input,opponent:lineup('c')});
assert.ok(opponent.opponentWin.delta>0);assert.ok(opponent.opponentWin.monteCarloSE<.005);
assert.equal(compareLineups({...input,opponent:{...lineup('c'),complete:false}}).opponentWin,null);
assert.equal(compareLineups({...input,recommended:lineup('b',true)}).status,'unavailable');
assert.ok(result.limitations.some(note=>note.includes('weather')));
const kicker={id:'k',name:'k',mean:7,positions:['K'],availability:'available',kickoff:300,projectionBounds:{low:7,high:9,reason:'missing distances'}};
const withK=lineup=>({...lineup,total:lineup.total+7,assignments:[...lineup.assignments,{index:1,slot:'K',playerId:'k',mean:7,locked:false}]});
const sharedK=compareLineups({...input,players:{...players,k:kicker},baseline:withK(input.baseline),recommended:withK(input.recommended),opponent:lineup('c')});
assert.equal(sharedK.status,'experimental');assert.ok(sharedK.gain);assert.equal(sharedK.baseline,null);assert.equal(sharedK.recommended,null);assert.equal(sharedK.opponentWin,null);
const changedKLineup=withK(input.recommended);changedKLineup.assignments[1].playerId='k2';
const changedK=compareLineups({...input,players:{...players,k:kicker,k2:{...kicker,id:'k2'}},baseline:withK(input.baseline),recommended:changedKLineup});
assert.equal(changedK.status,'unavailable');assert.equal(changedK.probabilityImproves,null);assert.equal(changedK.expectedGain,null);
const contingency=createContingencies({players,rosterIds:['b','early'],slots:['RB'],lineup:lineup('b'),currentStarters:['b'],now:100})[0];
assert.equal(contingency.lineup.assignments[0].playerId,'early');assert.equal(contingency.deadline,200);
const late=createContingencies({players,rosterIds:['b','early'],slots:['RB'],lineup:lineup('b'),currentStarters:['b'],now:250})[0];
assert.equal(late.lineup.complete,false);
console.log('weekly paired simulation and contingency fixtures passed');
