export type Pos = "QB" | "RB" | "WR" | "TE" | "K" | "DST";
export type Verdict = "buy" | "solid" | "risk" | "avoid";

/** [name, pos, team, adp, verdict, overallTier, posTier, note, tags] */
export type PlayerRow = [string, Pos, string, number, Verdict, number, number, string, string[]];

export const P: PlayerRow[] = [
["Jahmyr Gibbs","RB","DET",1.1,"solid",1,1,"Bellcow at last (Montgomery traded away). Easiest RB schedule in football, OPOY favorite. His 18 TDs will cool — the volume bump covers it.",["bell","reg","ceil"]],
["Bijan Robinson","RB","ATL",2.1,"solid",1,1,"Just made the highest-paid RB ever ($75M ext), and the goal-line work is all his — TD math projects UP (from 11 to ~13). Coin-flip with Gibbs; you can't miss.",["bell","floor","bnc"]],
["Ja'Marr Chase","WR","CIN",3.0,"solid",1,1,"30% target share, Burrow healthy, receiving-TD favorite. The safest elite pick on the board.",["floor", "ceil"]],
["Jaxon Smith-Njigba","WR","SEA",5.5,"solid",2,1,"Led the NFL with 1,793 yards — 44% of Seattle's receiving yards — then signed the biggest WR contract ever. History's honest: 1,700-yard seasons give back ~1,000 on average, but even the pullback version is a top-5 WR floor.",["floor", "reg"]],
["Amon-Ra St. Brown","WR","DET",7.1,"solid",2,1,"172 targets, machine-level consistency, Lions cruise all year including the fantasy playoffs.",["floor"]],
["Christian McCaffrey","RB","SF",6.2,"risk",2,2,"2025's overall fantasy MVP on earned volume, not luck. But: age 30, 450 touches, and Draft Sharks has him at 78% injury odds / 2.1 games missed — highest of any RB. Camp 'tightness' was one rest day. Conviction pick — eyes open.",["bell","age","inj"]],
["Puka Nacua","WR","LAR",4.1,"risk",2,1,"Best per-route receiver alive — with TWO live risks: the conduct ruling is still open (Schefter keeps a Week 1+ ban possible), and now a groin has him out of practice with McVay in no hurry (8/17). Zero games + healthy = top-4 pick. Check the news draft morning.",["susp", "ceil", "inj"]],
["Justin Jefferson","WR","MIN",11.1,"buy",2,1,"Still a buy: 30% target share even in 2025's broken offense, and Kyler (5th-most-accurate QB ever) is a massive upgrade. Two honest caps: Kyler's availability (41 of 68 games in four years) and his 17.5 passing-TD Vegas line — expect the bounce as catches-and-yards more than a TD spike.",["bnc", "ceil"]],
["Jonathan Taylor","RB","IND",7.8,"solid",2,2,"323 carries behind a top-10 line. But 20 TDs on a 14.4 expected — and 11 of the 13 backs to hit 18+ rushing TDs since 2000 declined the next year (avg -12). Round 1 yes, top-5 no.",["bell","reg","floor"]],
["James Cook","RB","BUF",10.1,"solid",2,2,"Goal-line back in a top-2 offense; 300+ carries. The quiet flag: 14 TDs on a 10.1 expected, and Allen vultures. New OC is expanding his receiving role — half-PPR likes that.",["bell","floor","reg"]],
["CeeDee Lamb","WR","DAL",9.7,"buy",2,1,"3 TDs on 6.6 expected, Pickens now drawing coverage, and the best Weeks 15-17 slate in football. Everything points up.",["bnc", "ceil"]],
["Derrick Henry","RB","BAL",17.1,"solid",2,2,"Still the bellcow at 32 — and the new OC publicly pledges 'no limits' plus MORE passing-game work. The interior line is the real worry; the mild discount is fair.",["bell","age","floor"]],
["Saquon Barkley","RB","PHI",13.8,"solid",3,2,"Elite O-line, true workhorse. Two knocks: he's 29 (the high-volume cliff starts here), and Philly's Wks 15-17 slate (@SEA, HOU, @SF) is the league's worst — the mirror of their easy regular season.",["bell","floor","age"]],
["Kenneth Walker III","RB","KC",14.4,"buy",3,2,"Super Bowl MVP, paid record FA money to be Mahomes' bellcow, camp reports rave about his screen usage. Market still prices the old boring KC backfield.",["bell","ceil"]],
["Chase Brown","RB","CIN",14.8,"solid",3,2,"Lead back in a top-4 Vegas offense. The market fully caught on — he's soared into round 2 (RB9-ish). ESPN home leagues still get him a full round late.",["bell","floor"]],
["A.J. Brown","WR","NE",19.0,"buy",3,2,"Traded to the #2 scoring offense with Drake Maye (led NFL in comp% + Y/A). Projected 130 targets. Alpha again.",["ceil"]],
["Drake London","WR","ATL",21.4,"solid",3,2,"28%+ target share in three of four seasons; 14.0 PPG when healthy. Quiet, elite floor.",["floor"]],
["Ashton Jeanty","RB","LV",12.0,"risk",3,3,"The staff is targeting 300-335 touches and signed Linderbaum to block for him. The drag: a bottom-tier offense with Cousins-now, rookie-Mendoza-later QB murk. Fine at 15-18; a reach at 10-12.",["bell","y2","bb"]],
["Brock Bowers","TE","LV",19.9,"solid",3,1,"The TE1. On pace to challenge McBride's 169-target record in a Kubiak scheme that feeds TEs. One caveat: Vegas's QB plan (Cousins now, rookie Mendoza looming). Take him here or punt the position.",["floor", "ceil"]],
["Omarion Hampton","RB","LAC",16.5,"solid",3,3,"'Most growth of anybody' per McDaniel, and PFF's #2 coaching-change riser (elite outside-zone fit). One honest caveat: McDaniel keeps saying all three backs will play. Lead role, not a monopoly.",["bell","y2","brk"]],
["George Pickens","WR","DAL",23.4,"buy",3,2,"137 targets last year, franchise-tagged, and the Cowboys are THE playoff-week stack (77.6 implied pts, Wks 15-17).",["ceil"]],
["Nico Collins","WR","HOU",23.1,"solid",3,2,"True alpha share, and Houston finally spent on the line (Teller trade, two new tackles). Rebuilt ≠ proven — fine at this price, don't take him earlier.",["floor"]],
["Malik Nabers","WR","NYG",23.7,"risk",3,2,"Trending toward Week 1 — best camp week yet (full-speed 11-on-11s, caught everything) — but the Giants admit an IR-to-Week-5 open is still possible. Upside WR2 price, WR1 ceiling, real tail risk. Your call.",["rec", "ceil", "bb"]],
["De'Von Achane","RB","MIA",17.2,"avoid",3,3,"The volume will be there (new staff floats 40-touch games). The fade: 12 TDs on 7.2 expected, 7+ injuries in four seasons, the NFL's lowest win total — and Willis-style mobile QBs historically starve RB targets, which was the Tua-fed half of his game. Not at a round-2 price.",["bell","inj","reg","bb"]],
["DeVonta Smith","WR","PHI",27.9,"buy",4,2,"A.J. Brown's exit makes him the unquestioned alpha for the first time. The consensus 'this year's JSN' candidate.",["brk", "floor"]],
["Breece Hall","RB","NYJ",28.4,"risk",4,3,"Paid $45M to stay, and Geno is a real QB upgrade — but he left practice TODAY (8/17) with a non-contact groin strain, timeline unknown. Get the injury news before you pay this price.",["bell","bnc","inj"]],
["Chris Olave","WR","NO",29.8,"solid",4,2,"20.2 PPG and 9.9 targets/game once Shough took over, then paid $132M this month. The room keeps thinning (Tyson out ~2 months) — volume locked in.",["floor"]],
["Emeka Egbuka","WR","TB",32.3,"buy",4,2,"Led ALL rookies with 127 targets; Evans' volume is his now. Fresh flag: sprained toe 8/13 and Bowles won't confirm Week 1 yet — verify draft morning. If healthy, the breakout consensus is earned.",["y2", "brk", "ceil"]],
["Rashee Rice","WR","KC",26.8,"risk",4,2,"Mahomes' WR1, no new suspension expected — but one healthy season in three and May knee surgery. WR1 price, WR2 risk profile.",["inj", "ceil"]],
["Trey McBride","TE","ARI",29.7,"risk",4,1,"TE-record 126 catches on 169 targets — now with Brissett confirmed at QB and a rookie RB eating checkdowns. Still consensus top-2 at the position; just priced for perfection.",["reg", "floor"]],
["Kyren Williams","RB","LAR",32.2,"buy",4,3,"RB7/RB7/RB9 three straight years, 66% of Rams red-zone work, #1 scoring offense. The Corum fear is your discount.",["bell","floor"]],
["Josh Allen","QB","BUF",36.3,"solid",4,1,"The only QB worth an early pick: top-2 at the position 5 of 6 years, 500+ rush yards five straight, now with DJ Moore. If he slides to Rd 3, sprint.",["floor", "ceil"]],
["Zay Flowers","WR","BAL",31.0,"solid",4,3,"5 TDs on 1,211 yards — 2nd-fewest of the 52 WRs to hit 1,200 since 2011 (group avg: 9.6) — and Baltimore just paid him $140M like a true WR1. The bounce is mathematically favored; Henry still owns the goal line.",["bnc", "cap"]],
["Ladd McConkey","WR","LAC",34.1,"buy",4,3,"McDaniel's new slot engine behind a healthier line. Classic scheme-tailwind bounce-back.",["brk", "bnc"]],
["Jeremiyah Love","RB","ARI",25.5,"risk",4,3,"#3 overall pick, a true three-down profile (11-for-58 in his debut before the injury). But the team's Week 1 hope fights high-ankle-sprain reality (2-3 month norm), and Conner AND Benson are hurt too. Pounce only if the ankle discounts him.",["comm","rk","bb","rec"]],
["Javonte Williams","RB","DAL",35.3,"solid",4,4,"287 touches and 13 total TDs last year, re-signed for $24M. New flag: explosive rookie Jaydon Blue is making camp noise (fumbles are his leash). Bankable floor, watch the split.",["bell","floor","cap"]],
["Tee Higgins","WR","CIN",35.1,"risk",4,3,"12 missed games in 3 years and 11 TDs on 6.5 expected. The talent is real; the price ignores both flags.",["inj", "reg"]],
["Tetairoa McMillan","WR","CAR",39.8,"solid",4,3,"Won Offensive Rookie of the Year over Egbuka — 122 targets, 1,014 yards — then added 8 lbs of muscle, and Canales is expanding his slot usage. The safer sophomore.",["y2", "floor"]],
["Jaylen Waddle","WR","DEN",38.5,"buy",4,3,"Traded (for a 1st) to PFF's #1 O-line, out of Miami's mess — camp calls his plays 'jaws-agape.' The leg strain cost him the preseason opener; Payton says minor. Confirm status, then buy.",["bnc", "ceil"]],
["Garrett Wilson","WR","NYJ",39.3,"solid",4,3,"30% target share when healthy and Geno helps — but the Jets added two 1st-round pass-catchers. Jets tax applies.",["floor"]],
["Cam Skattebo","RB","NYG",43.6,"solid",4,4,"Got the actual preseason start (workload eased as the ankle ramps), and Harbaugh brought Greg Roman specifically to pound the rock. Lead back with a goal-line profile; Tracy is the 1B.",["bell","y2","rec"]],
["Colston Loveland","TE","CHI",43.9,"buy",4,2,"'Unguardable' in camp; the TE2 in fantasy from Week 9 on (12 targets/game over the final month), and now the listed TE1 over Kmet in Ben Johnson's play-action game. Top-2 upside, TE3 price.",["y2", "brk", "ceil"]],
["Terry McLaurin","WR","WAS",47.1,"solid",4,3,"2025 was an injury mirage — a recurring quad limited him to 10 games (38-582-3), not a usage decline. Healthy now with the $96M extension long settled; Diggs takes a slice of the pie.",["bnc"]],
["Travis Etienne Jr.","RB","NO",42.4,"solid",4,4,"Paid $52M for the early downs — camp confirms a role-split committee: Etienne carries, Kamara catches. Solid volume floor in a bottom-10 offense.",["comm","floor","cap"]],
["Luther Burden III","WR","CHI",45.8,"risk",4,3,"Ben Johnson moves him everywhere — slot, outside, even backfield — not a pure Amon-Ra clone. The Aug 8 groin likely costs him all of preseason; Bears expect Wk 1. Take the discount, don't pay sticker.",["y2", "rec", "bb"]],
["D'Andre Swift","RB","CHI",47.6,"solid",4,4,"Ben Johnson's lead back in a rising offense — and Monangai's knee (out weeks) clears his early-season lane. Johnson's Detroit history says committee eventually; volume now.",["comm","floor","cap"]],
["David Montgomery","RB","HOU",47.3,"solid",4,4,"DeMeco is building a Lions-style TANDEM with Woody Marks — health, game-flow and matchups drive the split, so don't assume the goal line is all his. Rebuilt O-line helps the whole room.",["comm","floor","cap"]],
["Josh Jacobs","RB","GB",41.4,"avoid",4,4,"Out since Aug 5 (groin, 'at least' through preseason week 1 per LaFleur) with an open felony case the NFL is still weighing — a suspension could land mid-season with no warning. At Rd 3-4 cost, a landmine.",["bell","susp","inj"]],
["Rome Odunze","WR","CHI",58.4,"buy",5,4,"On breakout lists everywhere (SI, FantasyPros, Yahoo — Winks projects top-20): 41% of targets 15+ yards downfield, Moore AND Allen gone. He's the favorite in a live WR1 battle with Burden — watch final-preseason usage.",["brk","ceil"]],
["Mike Evans","WR","SF",48.9,"risk",5,3,"Pearsall's out for the year, so the targets are real. But he turns 33 with 12 missed games over two seasons, and his contested-catch game fights Shanahan's YAC scheme. Fair price, capped ceiling.",["age", "cap"]],
["Quinshon Judkins","RB","CLE",53.2,"solid",5,4,"'Looked 100%' after the ankle; locked starter with goal-line work. The league-worst O-line is the tax.",["bell","y2","floor","cap"]],
["DJ Moore","WR","BUF",53.3,"buy",5,4,"Traded into a top-2 offense where HC Joe Brady's system made 13 different Bills score TDs — priced like a WR27. Preseason ankle scare (8/15) called 'encouraging'; verify, then buy.",["bnc", "ceil"]],
["Lamar Jackson","QB","BAL",56.2,"buy",5,2,"The down 2025 was a hamstring, not decline. Top-2 QB upside at a round-5 price — the best QB value on the board.",["ceil", "bnc"]],
["Drake Maye","QB","NE",67.1,"buy",5,2,"QB2 overall last year, now throwing to A.J. Brown. If you miss Allen/Lamar, he's the pick.",["ceil"]],
["Jameson Williams","WR","DET",51.7,"solid",5,4,"Elite deep threat, but his production dips sharply when LaPorta is on the field — and a mid-August shoulder issue is limiting camp reps. Boom-bust WR3.",["bb"]],
["Bhayshul Tuten","RB","JAX",50.9,"risk",5,4,"The depth chart literally reads 'Tuten OR Rodriguez,' with Rodriguez ticketed for the goal line and LeQuint Allen for third downs — and JAX won't play starters in preseason, so it stays murky. Year-2 talent, committee price.",["comm","y2","bb","brk"]],
["Davante Adams","WR","LAR",52.2,"risk",5,4,"14 TDs — 9 from inside the 5 — drove 38% of his points on a career-worst 52.6% catch rate, and he turns 34 in December. Projections say ~10 TDs. The one comfort: he just proved age 33 can still be WR8.",["age", "reg"]],
["Bucky Irving","RB","TB",54.6,"risk",5,4,"'Chairman of a committee': success rate cratered to 41.6% (46th of 48) and Tampa gave him ZERO carries inside the 5 last year — Tucker owned them, and Gainwell was signed. Elite line keeps him afloat.",["comm","cap"]],
["Christian Watson","WR","GB",57.5,"solid",5,4,"Green Bay quietly traded away Doubs AND Wicks — someone has to catch the ball. Target-vacuum bet.",["bb"]],
["Tyler Warren","TE","IND",62.1,"buy",5,2,"817 yards as a rookie (a Colts TE record) plus a Pro Bowl nod, and Pittman's 100+ targets just left for Pittsburgh. Elite-TE volume at a round-6 price. Take him at cost.",["y2", "brk", "ceil"]],
["Carnell Tate","WR","TEN",61.7,"solid",5,4,"The safest rookie profile: instant WR1, elite capital, zero drops on 66 targets last year. Fresh flag: took a hard practice hit 8/17, evaluation pending — check status. Bottom-tier offense caps the ceiling.",["rk", "floor", "cap"]],
["TreVeyon Henderson","RB","NE",57.4,"risk",5,4,"Explosive (top-10 RB down the 2025 stretch), but the Patriots are now openly planning a 50-50 split — and his share is gated on pass-pro improvement. Price assumes a takeover nobody in the building is promising.",["comm","y2","bb","ceil"]],
["Jadarian Price","RB","SEA",61.9,"risk",5,4,"'Prime Dalvin Cook' burst (a teammate's actual quote) and back with the 1s — but the first depth chart briefly listed UDFA George Holani as starter during his soreness blip, and Charbonnet returns ~Wk 5-6. High-variance committee lead.",["comm","rk","bb","ceil"]],
["Brian Thomas Jr.","WR","JAX",64.0,"solid",5,4,"2025's headline bust — mostly QB chaos. Camp raves about a 'dominant offseason' and the Jags turned down multiple trade offers for him. Decent bounce-back odds at a two-round discount.",["bnc", "bb"]],
["Parker Washington","WR","JAX",58.7,"solid",5,4,"Three-list consensus breakout (14+ PPG from Week 9 on) — and Hunter's shift to full-time CB hands his target share a tailwind. He or Thomas is the alpha; both are startable.",["brk","bb"]],
["Joe Burrow","QB","CIN",68.4,"solid",5,2,"Vegas favorite to lead the NFL in passing yards AND TDs. The best stack partner alive (Chase, Higgins).",["floor", "ceil"]],
["Jayden Daniels","QB","WAS",69.6,"solid",5,2,"Rushing floor + a real WR duo now (McLaurin, Diggs). The wrinkle has a name: first-time play-caller David Blough, who wants more under-center work — camp says Daniels is 'accurate as he's ever been' in it.",["ceil"]],
["Marvin Harrison Jr.","WR","ARI",67.1,"risk",5,3,"The talent is not the question. An injury-wrecked 2025 (41-608-4 in 12 games), Vegas's bottom-2 offense and Brissett's low ceiling are. Bounce-back bet, not a proven WR1.",["bb","bnc"]],
["Jaylen Warren","RB","PIT",70.4,"solid",5,4,"Named camp RB1, but Dowdle is genuinely pushing to overtake him — McCarthy calls BOTH 'four-down backs.' Run-first offense keeps the pie big; the split is live.",["comm","cap"]],
["Rhamondre Stevenson","RB","NE",71.1,"solid",5,4,"His half of the now-official 50-50 committee comes with the early downs and short yardage, in the #2 scoring offense. Unsexy RB3 with RB2 weeks — and he's a round cheaper than Henderson.",["comm","floor","cap"]],
["Quentin Johnston","WR","LAC",74.7,"solid",5,4,"ADP up 31 spots this summer — McDaniel's scheme lifts the whole passing game. Momentum play.",["bb"]],
["DK Metcalf","WR","PIT",75.8,"risk",5,4,"Genuine analyst split: PFF calls him a top-3 coaching-change WINNER (McCarthy's offenses rank top-4 in deep shots), while others see Rodgers' quick game + Pittman capping him. Boom case is real; so is the WR3 floor.",["bb"]],
["Jalen Hurts","QB","PHI",72.8,"solid",5,3,"The rushing TDs always come. Note: the league's toughest Weeks 15-17 slate.",["floor"]],
["Caleb Williams","QB","CHI",73.2,"buy",5,3,"QB5 in year one under Ben Johnson, and camp says he's 'no longer drowning' — pre-snap mastered, designed runs being added. The year-2-in-scheme leap is the buy.",["ceil", "brk"]],
["Tony Pollard","RB","TEN",76.7,"solid",5,4,"Boring volume on a bad team. The foot has now cost him back-to-back practices (8/16-17) — beats call it minor, but check status draft morning.",["bell","floor","cap"]],
["Tucker Kraft","TE","GB",78.2,"solid",5,3,"ACL rehab ahead of schedule ('looks spectacular'). His TD rate will cool, but the thinned-out GB target tree helps.",["rec", "reg"]],
["Jayden Reed","WR","GB",79.6,"solid",5,4,"Doubs and Wicks are gone; Reed's slot role is the passing game's stable center.",["bb"]],
["Justin Herbert","QB","LAC",83.7,"buy",5,3,"McDaniel is explicitly speeding up his release behind a healthier line. The market prices last year's sacks, not this year's scheme.",["ceil"]],
["Dak Prescott","QB","DAL",80.8,"solid",5,3,"Led the NFL with 600 attempts; dome-heavy playoff slate. The QB half of the best playoff stack.",["floor"]],
["Josh Downs","WR","IND",81.8,"buy",5,4,"Projection models put him ~40 picks above this price as the Colts' top target-earner. Groin called 'not serious' by Steichen with a quick return expected — confirm he's practicing before you draft. Buy.",["brk"]],
["Courtland Sutton","WR","DEN",83.5,"solid",5,4,"Steady red-zone role in a rising offense — though Waddle's arrival caps the target share.",["floor", "cap"]],
["Rico Dowdle","RB","PIT",85.5,"solid",5,5,"The short-yardage half — and actively pushing Warren for the lead job per camp reports. TD-dependent flex with a real takeover path.",["comm","cap","brk"]],
["Trevor Lawrence","QB","JAX",86.5,"solid",5,4,"Resurgent under Coen (QB4 last year). Fine QB1 if you punted.",["floor"]],
["Brock Purdy","QB","SF",102.0,"buy",6,4,"~20 PPG when healthy — top-3 rate — and nobody drafts him. 'When healthy' is the catch: 9 of 17 games last year. Cheap enough to pair with a floor QB2.",["floor","inj"]],
["Chris Godwin Jr.","WR","TB",87.5,"solid",6,5,"Re-signed, reliable slot floor in a good offense; ceiling belongs to Egbuka. On ESPN he goes ~68 picks later than experts rank him — the biggest freebie on that platform.",["floor", "cap"]],
["Sam LaPorta","TE","DET",88.5,"solid",6,2,"Top-5 TE in a top-3 offense, priced round 8 because 2025 was 'only' good. Easy value if you punted TE.",["floor"]],
["Blake Corum","RB","LAR",89.5,"solid",6,5,"The #1 handcuff in fantasy — paced 900+ rushing yards over the last 10 games of 2025. Standalone flex value, league-winner if Kyren misses.",["comm","cuff","ceil"]],
["RJ Harvey","RB","DEN",88.0,"risk",6,5,"Explosive receiver, brutal runner: 3rd-worst rushing success rate and 4th-worst rush yards over expected last year — and Denver re-signed Dobbins and drafted Coleman anyway. PPR-week flex, not a breakout.",["comm","y2","reg","bb"]],
["Jordan Addison","WR","MIN",90.1,"solid",6,5,"TD-unlucky in 2025 and Kyler raises the boat — but a camp thumb injury is slowing the rapport-building. Solid WR4 with WR2 stretches.",["bnc"]],
["Jonathon Brooks","RB","CAR",78.8,"risk",6,5,"ADP up ~20 spots on health buzz — for 9 career carries and two ACL tears. Real explosiveness buzz, and he starts preseason G2 with Hubbard out — but Hubbard is still expected back Wk 1. Priced for the story.",["comm","inj","rec"]],
["Chuba Hubbard","RB","CAR",95.1,"risk",6,5,"Hamstring MRI, week-to-week, missed preseason G2 — Canales says 'very confident' for Wk 1. Check status draft morning; Brooks is breathing on his neck.",["bell","inj"]],
["J.K. Dobbins","RB","DEN",96.4,"risk",6,5,"Has never played a full season — though this camp's hamstring blip lasted exactly one day. The chart lists him RB1 ahead of Harvey. Great line, fragile bet.",["comm","inj"]],
["Patrick Mahomes","QB","KC",97.3,"risk",6,4,"Cleared and says the knee 'feels great' — but he's scaling back designed runs BY CHOICE to lean on Walker. The Konami floor that made him top-5 is gone either way. QB2 with a brand-name price.",["rec", "cap"]],
["Kyle Monangai","RB","CHI",98.6,"risk",6,5,"Worse than first reported: Fowler says the hyperextended knee costs him the rest of camp ('multiple weeks') and Week 1 is genuinely in doubt. Was Ben Johnson's TD sneak; now a wait-and-see.",["comm","y2","cap","rec"]],
["Michael Pittman Jr.","WR","PIT",99.3,"solid",6,5,"Traded to Pittsburgh; steady possession role in a run-first offense.",["floor", "cap"]],
["Stefon Diggs","WR","WAS",100.9,"buy",6,5,"Signed Aug 5 — the clear #2 opposite McLaurin with Daniels throwing. Biggest 7-day ADP riser in football (+33 spots) and slower platforms STILL lag. Move before your room catches up.",["bnc"]],
["Jordan Mason","RB","MIN",103.1,"buy",6,5,"Quietly winning Minnesota's backfield from an aging Aaron Jones (13.5 PPG as a 2025 fill-in). A starting RB in round 8-9.",["comm","brk","floor"]],
["Jaxson Dart","QB","NYG",101.6,"solid",6,4,"QB14 as a rookie on the strength of his legs (487 rush yds, 9 rush TDs); adds Likely and (eventually) Nabers. Small flag: several camp medical-tent visits. Fine late QB1.",["y2", "ceil"]],
["Xavier Worthy","WR","KC",105.1,"solid",6,5,"Fallen to a WR4 price and the models still flag him — but the split is brutal: with Rice on the field he's averaged ~2.7 catches and ~8 PPG. Ceiling dart that mostly needs a Rice absence.",["ceil", "bb"]],
["Matthew Golden","WR","GB",104.9,"buy",6,5,"Model-projected ~40 picks above price in a receiver room that just lost two starters.",["y2", "brk"]],
["Bo Nix","QB","DEN",107.0,"buy",6,4,"QB7 two straight years, best O-line in football, they traded a 1st for Waddle — and he's priced QB14. Buy.",["floor"]],
["Jacory Croskey-Merritt","RB","WAS",107.6,"buy",6,5,"The best efficiency profile (4.6 YPC, 8 TDs as a 7th-round rookie) in a genuinely OPEN six-back competition — charts disagree on the order and he's missed recent practice time. Models still love the price (+22 vs ADP); it's a bet, not a lock.",["comm","brk","bb"]],
["Kyle Pitts Sr.","TE","ATL",102.5,"risk",6,3,"19.0 PPG without London on the field, 9.6 with him. London is healthy — price him accordingly.",["bb", "cap"]],
["Harold Fannin Jr.","TE","CLE",102.4,"risk",6,4,"Small-sample 2025 magic meets an unresolved QB room (Watson vs. Sanders). Bull case: new HC Monken genuinely feeds TEs. You're paying for the encore, not a discount.",["y2", "reg"]],
["Matthew Stafford","QB","LAR",108.8,"risk",6,4,"Reigning MVP, 46 TDs at 38 — base rates say ~30 this year. Fine QB2; on ESPN his ADP runs two rounds hotter, don't chase it.",["age", "reg"]],
["Jared Goff","QB","DET",110.7,"solid",6,4,"Four straight 4,000-yard years; the Amon-Ra stack partner. Steady late QB1.",["floor", "cap"]],
["Kyler Murray","QB","MIN",113.5,"buy",6,4,"Named the Vikings' starter Aug 11 with Jefferson, Addison and Hockenson attached — still priced QB18. The late-round QB steal of 2026.",["bnc","ceil","inj"]],
["George Kittle","TE","SF",113.8,"risk",6,3,"Racing an aggressive Achilles timeline to Week 1. If the discount holds, low-end TE1 with spike weeks; any setback = Weeks 2-3.",["rec", "age"]],
["Rachaad White","RB","WAS",114.4,"solid",6,5,"Leads a genuinely open six-back battle on some charts — but Daniels' offenses target RBs at bottom-of-league rates (12.8-15.7%), so even the pass-catching floor is thinner than it looks. Don't pay for settled volume.",["comm","cap","bb"]],
["Khalil Shakir","WR","BUF",130.9,"buy",6,5,"Models put him ~57 picks above this price. Allen's most-trusted underneath target in a 26-point offense.",["floor"]],
["Wan'Dale Robinson","WR","TEN",111.6,"solid",6,5,"140 targets in 2025 (with NYG), now reunited with Daboll — whose offenses rank top-10 in slot targets — as Tennessee's volume piece. PPR-shaped, still fine in half.",["floor", "cap"]],
["Jakobi Meyers","WR","JAX",115.4,"solid",6,5,"Dependable target-earner in a top-6 scoring offense from 2025.",["floor", "cap"]],
["Makai Lemon","WR","PHI",82.5,"risk",6,6,"Round-1 pick with a real WR2 path — but this is his THIRD hamstring in 17 months, he's missed a week of camp, and the market is already correcting (-12 spots this week). Rd-12 dart, nothing more.",["rk", "rec", "bb", "inj"]],
["Jordan Love","QB","GB",116.3,"solid",6,5,"Volatile but the receiver-room churn hurts. Matchup-play QB2.",["bb"]],
["Kenneth Gainwell","RB","TB",109.5,"risk",6,5,"The passing-down slice of a three-way committee; Mayfield red-zone stack appeal only.",["comm","cap"]],
["Isaiah Likely","TE","NYG",125.7,"buy",6,4,"Giants paid him $40M and he's been Dart's clear top read while Nabers ramps up. The best TE-punt target.",["brk"]],
["Tyler Shough","QB","NO",125.5,"solid",6,5,"18+ PPG down his rookie stretch; added Etienne and (when healthy) Tyson. Sneaky QB2 with starter upside.",["y2", "brk"]],
["Malik Willis","QB","MIA",134.8,"solid",6,5,"The battle's over: 3yr/$67.5M, outplayed Ewers all camp, sealed it in the preseason opener. A 50+ rush-yds/game floor on a bad roster — streaming-QB gold.",["bb","brk"]],
["Baker Mayfield","QB","TB",121.8,"solid",6,5,"Elite line (Wirfs status worth a check), Egbuka stack — but Zac Robinson is his FIFTH OC in five years, the quiet continuity tax. Reliable late QB1-by-committee.",["floor"]],
["Jayden Higgins","WR","HOU",121.2,"solid",6,5,"Seized the clear #2 job opposite Nico — DeMeco flat-out: 'He's going to have a great year.' Big frame, real riser.",["y2", "brk"]],
["Romeo Doubs","WR","NE",118.3,"solid",6,5,"Paid $68M to be the WR2 opposite A.J. Brown in the #2 scoring offense — a defined role, not a camp hope. Sneaky depth with Maye throwing.",["cap","floor"]],
["Michael Wilson","WR","ARI",91.8,"solid",6,5,"2025's waiver MVP stretch was real, but the Cardinals tax (bottom-2 offense, QB mess) applies to him too.",["bb"]],
["Dalton Kincaid","TE","BUF",123.3,"risk",6,4,"Best per-route TE in football on a tiny snap share. The bet is 'more usage' — experts say the market already over-bet it.",["bb","reg","inj"]],
["De'Zhaun Stribling","WR","SF",126.4,"buy",7,5,"7-63 in his debut (led the game, all first half) after the sharp money moved first (+64 spots in a week). SF's room is decimated: Pearsall out for the year, Aiyuk unresolved, Kirk hurt. Real snaps are coming.",["rk", "brk", "bb"]],
["Denzel Boston","WR","CLE",140.3,"buy",7,5,"The camp riser of the summer: promoted to first team while incumbent Jerry Jeudy visibly struggles. Shedeur-vs-Watson QB murk is the only drag. Basically free.",["rk", "brk"]],
["Jake Ferguson","TE","DAL",134.0,"solid",7,4,"Dak's red-zone TE in the best playoff-schedule offense. Fine punt target.",["cap"]],
["Mark Andrews","TE","BAL",130.8,"risk",7,4,"Likely's exit helps, but experts have him among the most overdrafted TEs. Late only.",["age", "cap"]],
["Zach Charbonnet","RB","SEA",159.4,"buy",7,6,"'The most proven handcuff in football' — but PUP rules mean a realistic Week 5-6 debut. Elite stash IF you can float the roster spot for a month.",["comm","cuff","rec"]],
["MarShawn Lloyd","RB","GB",160.5,"buy",7,6,"The Jacobs contingency plan. High-stakes sharps moved him up 19 spots in a week — they're pricing the suspension risk.",["comm","cuff","bb"]],
["Tyler Allgeier","RB","ARI",148.1,"buy",7,6,"Took the BULK of first-team camp reps even before Love's sprain, and starts if Love isn't right (high-ankle norms say he may not be). Free insurance with a real early-season role.",["comm","cuff"]],
["Alvin Kamara","RB","NO",161.8,"solid",7,6,"Restructured to stay, and camp confirms he keeps the passing downs outright (Etienne gets the carries). Half-PPR trims his edge; the floor is real.",["comm","age","cap"]],
["Woody Marks","RB","HOU",141.6,"buy",7,6,"Not just insurance: DeMeco is explicitly building the Lions' Gibbs/Monty tandem with Marks in the Gibbs role. 5 TDs on 7.8 expected says positive regression too. Deep-league gold.",["comm","y2","bnc"]],
["Rashid Shaheed","WR","SEA",133.8,"solid",7,6,"Seattle's field-stretcher; JSN's gravity leaves him single coverage.",["bb"]],
["Deebo Samuel Sr.","WR","SF",128.0,"risk",7,6,"Healthy and 'explosive, lean' per camp, and Pearsall's season-ending injury feeds him targets — sharps moved him up 35-50 spots. But four straight years of hot-start-then-hurt is still the profile.",["inj", "age"]],
["Dallas Goedert","TE","PHI",135.1,"avoid",7,5,"11 TDs on 60 catches (5.1 expected) — statistically extreme, and the market agrees: he went unsigned into free agency before a $7M one-year deal. Projections say TE20.",["age", "reg"]],
["Sam Darnold","QB","SEA",142.2,"solid",7,5,"Super Bowl-winning continuity; fine streamer with a champion's schedule.",["floor"]],
["Daniel Jones","QB","IND",146.8,"solid",7,5,"Locked-in starter and the camp's been clean — though national reporting (8/17) questions whether the pre-Achilles wheels are all the way back, which caps the rushing floor. Stabilizes the Colts.",["rec", "floor"]],
["C.J. Stroud","QB","HOU",145.5,"solid",7,5,"Improved AFC South schedule; O-line still the anchor dragging him down.",["cap"]],
["T.J. Hockenson","TE","MIN",170.3,"solid",7,4,"The Kyler lift is the theory; early usage is thin (5 snaps in the preseason opener). Free TE with spike weeks if the targets come — streamer until they do.",["bnc","cap"]],
["Oronde Gadsden II","TE","LAC",167.5,"solid",7,4,"McDaniel schemes touches to TEs — but the trade for David Njoku (a camp standout) splits that pie three ways. Deep-league punt, watch the usage.",["y2", "brk", "cap"]],
["Travis Kelce","TE","KC",122.7,"avoid",7,4,"Turns 37 with yards-per-target down four straight years (6.9 the last two vs 8.6 career), and Rice + Walker eat his targets. The name costs three rounds more than the player.",["age", "reg"]],
["Isiah Pacheco","RB","DET",168.9,"solid",7,6,"Signed with Detroit — the direct Gibbs handcuff in the league's best RB environment. Nursing a sprained MCL, but Campbell expects him ready Week 1.",["comm","cuff"]],
["Tyrone Tracy Jr.","RB","NYG",136.6,"solid",7,6,"Trending toward the change-of-pace/passing-down half after Skattebo got the preseason start — still the direct insurance in a run-heavy scheme.",["comm","cuff"]],
["Tank Bigsby","RB","PHI",151.1,"solid",7,6,"The direct Saquon handcuff behind the league's best line — and Philly is openly using him to MANAGE Saquon's workload, so there's standalone touch value too. Zero-RB stash.",["comm","cuff","bb"]],
["Tyjae Spears","RB","TEN",157.9,"solid",7,6,"Pollard insurance with standalone passing-down work.",["comm","cuff"]],
["Keaton Mitchell","RB","LAC",130.8,"risk",7,6,"Explosive space player McDaniel could scheme for — but he was a healthy inactive in the preseason opener while Vidal played. The RB2 job is unresolved. Boom-or-bench.",["comm","bb"]],
["Jalen Coker","WR","CAR",129.4,"risk",7,6,"Carolina paid him $35M, but the 2025 sample was 33 catches in 11 games and Legette is real competition. Upside dart, not established volume.",["brk","bb"]],
["Dontayvion Wicks","WR","PHI",166.3,"solid",7,6,"Fowler says the org is 'really excited' — and his WR2 competition (a scuffling Hollywood Brown) is beatable. Cheap route to real snaps in a thin room.",["bb","brk"]],
["Zachariah Branch","WR","ATL",184.4,"buy",7,6,"50-yard TD in his first padded practice and the story of Falcons camp — though the slot's 1st-team reps still run through Zaccheaus. Path to WR2 for free; not there yet.",["rk", "brk"]],
["Jordyn Tyson","WR","NO",69.1,"risk",7,6,"Elite rookie profile, clear #2 role — but Rapoport says the new hamstring costs him ~2 months (mid-late October). The best-ball ADP is stale by a mile; rd-14 stash or waiver add.",["rk", "rec"]],
["Omar Cooper Jr.","WR","NYJ",155.5,"risk",7,6,"Fading: camp 'pitfalls' per his own WR coach, and Adonai Mitchell has the #2 job behind Wilson. Round-1 pedigree, last-round flier only.",["rk", "bb"]],
["Travis Hunter","WR","JAX",148.9,"risk",7,5,"Trending the wrong way for fantasy: listed at starting CB and SECOND-string WR, with defensive reps climbing all camp (final commitment withheld until it counts). Talent's real; the WR snaps may not be.",["y2", "cap"]],
["Keon Coleman","WR","BUF",210.0,"solid",7,6,"Has functionally locked the WR3 job (camp buzz + a preseason TD) in a top-2 offense. Banged up scoring it — check status. Last-round flier with a real role.",["bb"]],
["Cooper Kupp","WR","SEA",211.1,"solid",7,6,"Still in Seattle, still crafty — deep-league depth only at this stage.",["age", "cap"]],
["Kenyon Sadiq","TE","NYJ",178.5,"risk",7,5,"Fastest TE forty ever recorded (4.39), but the hernia setback costs him ~2 weeks (Glenn still expects Wk 1) in a crowded, low-scoring passing game. Dynasty > redraft.",["rk", "rec"]],
["Kaytron Allen","RB","WAS",211.5,"buy",7,6,"6th-round 'Fatman' who flashed in preseason (23-85-1 vs Miami) with a short-yardage path — though pass-pro concerns reportedly threaten his roster spot. Free last-round swing.",["comm","rk","cuff","bb"]],
["Aaron Jones Sr.","RB","MIN",126.3,"risk",7,5,"2,000+ career touches and Mason is visibly taking over. The fade side of the Minnesota backfield.",["comm","age","cap"]],
["Alec Pierce","WR","IND",55.0,"risk",7,5,"The market drafts him top-60, but he's on PUP after offseason foot surgery with zero camp reps — team says Wk 1, believe it when he practices. Deep-ball WR3 when right.",["rec","bb"]],
["Adonai Mitchell","WR","NYJ",120.0,"solid",7,5,"The other half of the Sauce Gardner trade is winning the Jets' #2 job — 'breakout candidate' per beat writers, now ahead of Cooper. Cheap path to real snaps.",["y2","brk"]],
["David Njoku","TE","LAC",150.0,"solid",7,4,"Traded in and instantly one of Chargers camp's standouts — McDaniel's TE-friendly scheme now has a proven pass-catcher in it. Late TE with spike weeks.",["floor","cap"]],
["Braelon Allen","RB","NYJ",165.0,"buy",7,6,"Breece's direct handcuff just became urgent — Hall strained his groin 8/17 — and Allen flashed in the preseason opener (31-yd TD). Add before your league reads the news.",["comm","cuff","bb"]],
["Ray Davis","RB","BUF",146.0,"solid",7,6,"James Cook's direct backup in an offense about to feed the RB room more (Carmichael scheme). Standard-issue high-value handcuff.",["comm","cuff"]],
["Chris Rodriguez Jr.","RB","JAX",154.0,"solid",7,6,"The other half of 'Tuten OR Rodriguez' — coaches have sketched him the goal-line role. TD-vulture flex if the split sticks.",["comm","bb"]],
["Jaydon Blue","RB","DAL",180.0,"risk",7,6,"'Elite explosiveness' per camp — the one real threat to Javonte's workload — but fumbles cap the trust. Dart with a path.",["rk","bb"]],
["Brian Robinson Jr.","RB","ATL",190.0,"solid",7,6,"Signed to back up the highest-paid RB ever — the real Bijan handcuff in a run-first Stefanski scheme.",["comm","cuff"]],
["Ja'Kobi Lane","WR","BAL",185.0,"buy",7,6,"'Best Ravens WR camp in 27 years' per the beat, TD in the preseason opener, and the new OC wants to spread it around. Free upside.",["rk","brk"]],
["Malachi Fields","WR","NYG",200.0,"buy",7,6,"3rd-rounder the Giants traded up for, making a corroborated claim on the #2 job while Nabers ramps. Harbaugh: 'didn't play like a rookie.'",["rk","brk"]],
["Malik Benson","WR","LV",205.0,"solid",7,6,"'Vegas' biggest camp surprise' — first-team reps per the head coach. Role still fluid; watch cuts.",["rk","bb"]],
["Elic Ayomanor","WR","TEN",198.0,"solid",7,6,"Year-2 riser racing Tate for camp-standout honors — 2nd on the team in receiving as a rookie. Deep-league WR depth.",["y2","brk"]],
["Aaron Rodgers","QB","PIT",180.4,"solid",7,5,"'Zero debate' — his final season, reunited with McCarthy (his 13-year Packers HC) in a run-first, play-action scheme. Streamer at best — but a fine bye-week QB.",["age", "cap"]]
];

export const OT: Record<number, [string, string]> = {
  1: ["The Big Three", "picks 1–3"],
  2: ["Elite Anchors", "round 1"],
  3: ["Rounds 2–3 Pillars", "the last bellcows & alpha WRs"],
  4: ["Rounds 3–5", "last of the locks"],
  5: ["Rounds 5–8", "the value zone"],
  6: ["Rounds 8–11", "role bets & late QBs"],
  7: ["Rounds 12–15", "darts, cuffs & stashes"],
};

export const PT: Record<string, Record<number, [string, string]>> = {
  QB: { 1: ["The Exception", "Allen — the only early QB"], 2: ["Difference-Makers", "rounds 5–7"], 3: ["Set-and-Forget", "rounds 6–8"], 4: ["The Value Shelf", "rounds 8–11 — wait & win"], 5: ["Streamers", "rounds 12+ / waivers"] },
  RB: { 1: ["The 1.01 Debate", "picks 1–2"], 2: ["True Bellcows", "rounds 1–2"], 3: ["High-End RB2s", "rounds 2–3 — talent or situation, pick one"], 4: ["The Dead Zone", "rounds 4–7 — tread carefully"], 5: ["Role Bets", "rounds 7–10"], 6: ["Handcuffs & Darts", "rounds 11+"] },
  WR: { 1: ["Alphas", "rounds 1–2"], 2: ["WR1s With a Catch", "rounds 2–3"], 3: ["Strong WR2s", "rounds 3–5"], 4: ["Flex With Upside", "rounds 5–8"], 5: ["Bench Value", "rounds 8–12 — the model darlings"], 6: ["Darts & Stashes", "rounds 13+"] },
  TE: { 1: ["Pay Up or Move On", "round 2–3"], 2: ["The Smart Middle", "rounds 4–8"], 3: ["Talent & Health Gambles", "rounds 8–10"], 4: ["Punt Targets", "rounds 10+"], 5: ["Streamers", "late / waivers"] },
};

export const VLBL: Record<Verdict, string> = { buy: "VALUE", solid: "SOLID", risk: "RISKY", avoid: "AVOID" };

export const TAGS: Record<string, [string, string]> = {
  bell: ["Bellcow", "The backfield is his — carries AND catches"],
  comm: ["Committee", "Splits the backfield — capped weekly role"],
  ceil: ["High ceiling", "Legit league-winning upside"],
  floor: ["High floor", "Safe weekly points"],
  cap: ["Low ceiling", "Useful, but rarely wins you a week"],
  bb: ["Boom-bust", "Big weeks and zero weeks"],
  inj: ["Injury-prone", "Multi-year pattern of missed games"],
  rec: ["Returning", "Coming back from a major injury"],
  age: ["Age risk", "Wrong side of the aging curve"],
  reg: ["TD regression", "Scored more TDs than his chances predict — expect fewer"],
  bnc: ["Bounce-back", "Unlucky or broken 2025 — expect more"],
  brk: ["Breakout bet", "Role or situation just opened up"],
  rk: ["Rookie", "First NFL season"],
  y2: ["Year 2", "Second-season leap candidate"],
  cuff: ["Handcuff", "Backup who inherits a big role on injury"],
  susp: ["Suspension risk", "League discipline pending"],
};

export const TAGCLASS: Record<string, string> = {
  inj: "warn", susp: "warn", reg: "warn", age: "warn",
  ceil: "good", brk: "good", bnc: "good", floor: "good", bell: "good",
};

export const BYE: Record<string, number> = {
  KC: 5, CAR: 5, CIN: 6, DET: 6, MIA: 6, MIN: 6, BUF: 7, JAX: 7, LAC: 7, WAS: 7,
  HOU: 8, NO: 8, NYG: 8, SF: 8, PIT: 9, TEN: 9, CHI: 10, DEN: 10, PHI: 10, TB: 10,
  ATL: 11, CLE: 11, GB: 11, LAR: 11, NE: 11, SEA: 11, BAL: 13, IND: 13, LV: 13, NYJ: 13,
  ARI: 14, DAL: 14,
};

export const CUFFS: Record<string, string> = {
  "Kyren Williams": "Blake Corum",
  "Jahmyr Gibbs": "Isiah Pacheco",
  "Saquon Barkley": "Tank Bigsby",
  "Jeremiyah Love": "Tyler Allgeier",
  "Josh Jacobs": "MarShawn Lloyd",
  "Cam Skattebo": "Tyrone Tracy Jr.",
  "Tony Pollard": "Tyjae Spears",
  "James Cook": "Ray Davis",
  "Breece Hall": "Braelon Allen",
  "Bijan Robinson": "Brian Robinson Jr.",
};

/** [team, implied PPG, weeks 15–17 implied total] */
export const VEGAS: [string, number, number][] = [
  ["Rams",26.7,78.8], ["Bills",26.1,79.0], ["Lions",26.1,75.0], ["Bengals",26.0,79.0],
  ["Ravens",25.9,75.8], ["Cowboys",25.7,77.6], ["49ers",25.0,67.8], ["Packers",24.8,73.5],
  ["Seahawks",24.8,69.5], ["Bears",24.6,74.0], ["Chiefs",24.1,70.8], ["Chargers",23.8,74.8],
  ["Patriots",23.8,67.5], ["Eagles",23.8,64.5], ["Jaguars",23.5,70.6], ["Commanders",23.5,69.5],
  ["Colts",23.4,73.0], ["Buccaneers",23.3,70.0], ["Texans",22.5,60.8], ["Vikings",22.4,68.5],
  ["Broncos",22.3,65.5], ["Giants",22.1,67.5], ["Falcons",21.8,66.5], ["Saints",21.5,67.5],
  ["Steelers",21.4,66.5], ["Panthers",20.8,60.0], ["Titans",20.6,64.0], ["Raiders",19.2,62.5],
  ["Browns",18.7,55.3], ["Jets",18.5,56.5], ["Cardinals",18.4,60.0], ["Dolphins",17.9,56.8],
];

/** Live market data — FantasyFootballCalculator half-PPR 12-team ADP, 2,372 real drafts Aug 12-17 2026.
 *  Per player: [market ADP, std dev, earliest pick seen, latest pick seen]. Refresh via the FFC API
 *  (free, no key): https://fantasyfootballcalculator.com/api/v1/adp/half-ppr?teams=12&year=2026 */
export const MKT: Record<string, [number, number, number, number]> = {"Jahmyr Gibbs":[1.5,0.7,1,3],"Bijan Robinson":[2.0,0.7,1,3],"Ja'Marr Chase":[4.1,0.9,1,7],"Jaxon Smith-Njigba":[5.4,1.3,2,8],"Amon-Ra St. Brown":[7.6,1.5,3,12],"Justin Jefferson":[14.1,2.2,8,20],"Christian McCaffrey":[6.8,1.6,3,11],"Puka Nacua":[3.0,0.5,1,4],"Jonathan Taylor":[5.9,1.3,3,10],"James Cook":[8.9,2.0,3,16],"CeeDee Lamb":[12.7,2.2,6,18],"Derrick Henry":[10.5,1.5,6,15],"Saquon Barkley":[18.0,3.2,9,28],"Kenneth Walker III":[22.5,4.0,11,32],"Chase Brown":[15.0,2.6,9,22],"A.J. Brown":[18.8,2.9,12,28],"Drake London":[11.8,1.5,9,15],"Ashton Jeanty":[15.7,2.8,8,23],"Brock Bowers":[41.9,9.4,17,61],"Omarion Hampton":[22.2,3.9,12,30],"George Pickens":[19.3,2.5,15,29],"Nico Collins":[21.1,2.3,16,29],"Malik Nabers":[27.3,3.3,18,38],"De'Von Achane":[11.6,2.2,5,18],"DeVonta Smith":[31.2,3.5,22,42],"Breece Hall":[29.0,2.7,23,35],"Chris Olave":[24.3,2.5,17,31],"Emeka Egbuka":[36.9,5.2,23,54],"Rashee Rice":[16.2,2.1,12,20],"Trey McBride":[38.5,6.9,20,50],"Kyren Williams":[27.4,3.4,18,34],"Josh Allen":[31.0,6.3,14,45],"Zay Flowers":[24.3,2.6,18,31],"Ladd McConkey":[40.6,4.2,29,57],"Jeremiyah Love":[32.1,4.4,21,45],"Javonte Williams":[34.9,4.4,23,47],"Tee Higgins":[34.8,3.9,24,47],"Tetairoa McMillan":[33.7,3.9,23,43],"Jaylen Waddle":[46.8,5.7,34,63],"Garrett Wilson":[30.7,3.3,22,44],"Cam Skattebo":[35.0,4.0,24,46],"Colston Loveland":[60.1,8.0,39,78],"Terry McLaurin":[44.7,4.4,36,59],"Travis Etienne Jr.":[42.8,5.3,29,55],"Luther Burden III":[59.8,7.0,42,81],"D'Andre Swift":[43.3,6.5,30,59],"David Montgomery":[55.5,5.3,41,70],"Josh Jacobs":[26.9,2.6,20,34],"Mike Evans":[52.3,6.3,35,79],"Quinshon Judkins":[52.3,5.4,38,62],"DJ Moore":[49.5,5.8,36,68],"Lamar Jackson":[56.2,8.6,33,67],"Jameson Williams":[39.4,4.5,27,53],"Bhayshul Tuten":[53.6,5.4,39,65],"Davante Adams":[37.2,3.3,28,46],"Bucky Irving":[47.8,6.1,31,64],"Christian Watson":[56.9,5.8,42,72],"Rome Odunze":[45.9,4.9,33,60],"Tyler Warren":[69.7,8.9,46,86],"Carnell Tate":[72.9,7.3,53,89],"TreVeyon Henderson":[58.5,5.6,44,71],"Jadarian Price":[78.8,11.1,49,117],"Brian Thomas Jr.":[70.2,8.0,49,92],"Parker Washington":[65.1,6.8,47,81],"Drake Maye":[51.5,7.1,33,67],"Joe Burrow":[55.0,10.0,28,71],"Jayden Daniels":[71.8,10.6,44,109],"Marvin Harrison Jr.":[63.3,7.1,44,80],"Jaylen Warren":[64.2,6.1,48,80],"Rhamondre Stevenson":[69.7,7.1,51,91],"Quentin Johnston":[84.4,8.3,62,104],"DK Metcalf":[62.7,7.2,43,80],"Jalen Hurts":[77.4,11.2,50,111],"Caleb Williams":[86.0,13.0,54,121],"Tony Pollard":[65.4,6.4,53,82],"Tucker Kraft":[94.1,15.2,54,144],"Jayden Reed":[90.3,7.4,70,104],"Justin Herbert":[107.5,14.1,70,139],"Dak Prescott":[66.4,8.0,45,89],"Josh Downs":[84.0,8.7,61,102],"Courtland Sutton":[61.2,5.9,50,77],"Rico Dowdle":[77.8,7.3,63,97],"Trevor Lawrence":[94.7,13.4,59,126],"Chris Godwin Jr.":[78.1,8.2,56,104],"Sam LaPorta":[90.3,15.0,51,148],"Blake Corum":[123.0,13.7,87,146],"RJ Harvey":[87.5,11.2,65,115],"Jordan Addison":[91.0,9.7,65,118],"Jonathon Brooks":[110.5,17.6,65,142],"Chuba Hubbard":[71.9,6.3,58,90],"J.K. Dobbins":[88.7,10.9,66,122],"Patrick Mahomes":[100.1,13.4,65,129],"Kyle Monangai":[113.9,14.7,75,147],"Michael Pittman Jr.":[81.2,7.6,61,99],"Stefon Diggs":[96.2,10.1,70,115],"Jordan Mason":[114.6,17.2,74,146],"Jaxson Dart":[119.8,14.2,82,141],"Brock Purdy":[86.6,12.5,63,117],"Xavier Worthy":[101.3,7.9,80,117],"Matthew Golden":[108.6,9.9,82,135],"Bo Nix":[116.5,15.9,75,140],"Jacory Croskey-Merritt":[110.3,14.1,73,145],"Kyle Pitts Sr.":[81.7,6.6,68,93],"Harold Fannin Jr.":[81.2,6.8,63,101],"Matthew Stafford":[76.5,13.0,42,116],"Jared Goff":[104.1,12.0,76,126],"Kyler Murray":[137.0,18.4,89,174],"George Kittle":[117.1,20.2,64,164],"Rachaad White":[112.1,13.5,77,138],"Wan'Dale Robinson":[94.1,7.8,73,111],"Jakobi Meyers":[88.8,8.1,67,101],"Makai Lemon":[107.8,9.8,82,125],"Jordan Love":[148.4,11.4,119,172],"Kenneth Gainwell":[101.8,12.6,74,138],"Isaiah Likely":[136.8,19.1,95,177],"Tyler Shough":[132.6,12.7,99,159],"Baker Mayfield":[133.4,10.8,105,150],"Jayden Higgins":[119.6,10.6,93,144],"Romeo Doubs":[108.5,6.4,91,120],"Michael Wilson":[75.0,7.9,54,90],"Dalton Kincaid":[142.5,21.2,87,171],"Khalil Shakir":[104.5,7.6,84,117],"De'Zhaun Stribling":[143.5,17.3,98,178],"Denzel Boston":[140.6,15.3,100,179],"Jake Ferguson":[148.7,16.8,105,177],"Mark Andrews":[128.3,19.1,79,159],"Zach Charbonnet":[133.1,17.8,86,169],"MarShawn Lloyd":[166.3,14.4,133,178],"Tyler Allgeier":[160.2,19.5,116,209],"Alvin Kamara":[148.8,19.4,98,180],"Woody Marks":[144.9,11.5,126,169],"Travis Hunter":[155.9,21.1,101,180],"Rashid Shaheed":[121.4,8.9,98,140],"Deebo Samuel Sr.":[108.0,10.2,81,124],"Dallas Goedert":[112.8,18.9,72,147],"Malik Willis":[165.9,12.4,136,191],"Sam Darnold":[148.0,20.0,96,169],"Daniel Jones":[165.7,11.0,137,179],"C.J. Stroud":[164.2,9.9,143,176],"T.J. Hockenson":[168.3,24.0,117,205],"Travis Kelce":[121.8,18.6,73,164],"Isiah Pacheco":[150.9,24.2,87,200],"Tyrone Tracy Jr.":[148.4,17.1,103,177],"Tank Bigsby":[166.0,21.4,119,205],"Tyjae Spears":[150.3,15.4,114,173],"Keaton Mitchell":[151.3,20.3,108,182],"Jalen Coker":[114.2,10.3,87,143],"Dontayvion Wicks":[166.2,23.4,144,191],"Jordyn Tyson":[95.1,9.4,74,116],"Omar Cooper Jr.":[167.5,8.1,150,178],"Cooper Kupp":[147.3,18.6,98,178],"Aaron Jones Sr.":[99.8,12.6,73,125]};

/** The news feed — newest entry first. The daily refresh routine PREPENDS an entry each run.
 *  dir: "up" = good for the player's draft stock, "down" = bad. */
export type NewsItem = { text: string; player?: string; dir?: "up" | "down" };
export const NEWS: { when: string; items: NewsItem[] }[] = [
  {
    when: "Aug 17, 2026 \u00b7 9:15 PM PT",
    items: [
      { player: "Breece Hall", dir: "down", text: "Left practice with a non-contact groin strain (8/17), timeline unknown \u2014 verify before paying his round-3 price." },
      { player: "Emeka Egbuka", dir: "down", text: "Sprained toe (8/13); Bowles won't confirm Week 1 yet \u2014 check draft morning." },
      { player: "Puka Nacua", dir: "down", text: "Groin has him out of practice, stacked on the still-open conduct ruling." },
      { player: "Carnell Tate", dir: "down", text: "Evaluated after a hard practice hit (8/17), severity unknown." },
      { player: "Malik Willis", dir: "up", text: "Named Miami's starter (3yr/$67.5M) \u2014 late-round rushing-floor streamer unlocked." },
      { player: "Jacory Croskey-Merritt", dir: "up", text: "Listed RB1 on Washington's first depth chart in a genuinely open six-back battle." },
      { text: "ADP refreshed from 2,372 live half-PPR drafts (Aug 12-17); board grown to 170 players with Sleeper live data wired in." },
    ],
  },
];

/** League draft order — "charmin ultra strong", confirmed by the owner. */
export const DRAFT_ORDER = ["Ashley","Zach","Jeff","Brandon","Duy","Brian JK","Michelle","Aaron","Matt","Emily","Josh","Brian V"];
/** The slots of the people who use this tool, for one-tap identity. */
export const TOOL_USERS: [string, number][] = [["Ashley", 1], ["Brian JK", 6], ["Emily", 10]];

/** Winning opening line per seat from 800 risk-adjusted Monte Carlo drafts
 *  (see app/scripts/draft-sim.mjs). Each pick lists who the sim actually landed,
 *  most likely first — so the 2nd/3rd names are your fallbacks. */
export type SimPick = { pick: number; opts: [string, number][] };
export const SIM_PLANS: Record<number, { strategy: string; ppw: number; winPct: number; picks: SimPick[] }> = {
  1: {
    strategy: "Double-RB off the 1.01",
    ppw: 110.5,
    winPct: 98,
    picks: [
      { pick: 1, opts: [["Jahmyr Gibbs", 100]] },
      { pick: 24, opts: [["Breece Hall", 68], ["Kenneth Walker III", 31]] },
      { pick: 25, opts: [["George Pickens", 64], ["A.J. Brown", 20], ["Nico Collins", 15]] },
      { pick: 48, opts: [["Jaylen Waddle", 38], ["Ladd McConkey", 33], ["Emeka Egbuka", 23]] },
      { pick: 49, opts: [["Colston Loveland", 93], ["Tyler Warren", 7]] },
      { pick: 72, opts: [["Justin Herbert", 59], ["Trevor Lawrence", 20]] },
    ],
  },
  6: {
    strategy: "Double-RB",
    ppw: 109.0,
    winPct: 93,
    picks: [
      { pick: 6, opts: [["Christian McCaffrey", 72], ["Jonathan Taylor", 20], ["James Cook", 8]] },
      { pick: 19, opts: [["Kenneth Walker III", 70], ["Saquon Barkley", 25]] },
      { pick: 30, opts: [["Malik Nabers", 72], ["Nico Collins", 14], ["DeVonta Smith", 9]] },
      { pick: 43, opts: [["Emeka Egbuka", 69], ["Ladd McConkey", 16], ["DeVonta Smith", 9]] },
      { pick: 54, opts: [["Colston Loveland", 66], ["Tyler Warren", 33]] },
      { pick: 67, opts: [["Justin Herbert", 65], ["Jalen Hurts", 16]] },
    ],
  },
  10: {
    strategy: "Hero RB, then receivers",
    ppw: 108.0,
    winPct: 83,
    picks: [
      { pick: 10, opts: [["Derrick Henry", 56], ["Saquon Barkley", 23], ["James Cook", 17]] },
      { pick: 15, opts: [["A.J. Brown", 48], ["Justin Jefferson", 45], ["CeeDee Lamb", 7]] },
      { pick: 34, opts: [["DeVonta Smith", 62], ["Malik Nabers", 34]] },
      { pick: 39, opts: [["Javonte Williams", 55], ["Cam Skattebo", 40]] },
      { pick: 58, opts: [["Tyler Warren", 57], ["Colston Loveland", 36]] },
      { pick: 63, opts: [["Justin Herbert", 56], ["Jalen Hurts", 29]] },
    ],
  },
};
