export type Pos = "QB" | "RB" | "WR" | "TE" | "K" | "DST";
export type Verdict = "buy" | "solid" | "risk" | "avoid";

/** [name, pos, team, adp, verdict, overallTier, posTier, note, tags] */
export type PlayerRow = [string, Pos, string, number, Verdict, number, number, string, string[]];

export const P: PlayerRow[] = [
["Jahmyr Gibbs","RB","DET",1.1,"solid",1,1,"Bellcow at last (Montgomery traded away). Easiest RB schedule in football, OPOY favorite. His 18 TDs will cool — the volume bump covers it.",["bell","reg","ceil"]],
["Bijan Robinson","RB","ATL",2.1,"solid",1,1,"Elite line, and the goal-line work is all his now — TD math points UP (13 projected). Coin-flip with Gibbs; you can't miss.",["bell","floor","bnc"]],
["Ja'Marr Chase","WR","CIN",3.0,"solid",1,1,"30% target share, Burrow healthy, receiving-TD favorite. The safest elite pick on the board.",["floor","ceil"]],
["Jaxon Smith-Njigba","WR","SEA",5.5,"solid",2,1,"Led the NFL with 1,793 yards on a 44% share of Seattle's passing. Some pullback is priced in; the floor is rock-solid.",["floor","reg"]],
["Amon-Ra St. Brown","WR","DET",7.1,"solid",2,1,"172 targets, machine-level consistency, Lions cruise all year including the fantasy playoffs.",["floor"]],
["Justin Jefferson","WR","MIN",11.1,"buy",2,1,"The clearest buy on the board: top-7 targets, league-worst TD luck (2 scored vs 8 expected), and a real QB now in Kyler. Top-5 profile at pick 11.",["bnc","ceil"]],
["Christian McCaffrey","RB","SF",6.2,"risk",2,2,"2025's overall fantasy MVP on earned volume, not luck. But: age 30, 450 touches, camp 'tightness,' 78% injury-model risk. Conviction pick — eyes open.",["bell","age","inj"]],
["Puka Nacua","WR","LAR",4.1,"risk",2,1,"Best per-route receiver alive in the NFL's best offense (107.5-catch Vegas line). One problem: suspension ruling pending. Check the news, then decide.",["susp","ceil"]],
["Jonathan Taylor","RB","IND",7.8,"solid",2,2,"323 carries behind a top-10 line, led NFL in goal-line points. 20 TDs → expect ~14. Round 1 yes, top-5 no.",["bell","reg","floor"]],
["James Cook","RB","BUF",10.1,"solid",2,2,"Goal-line back in a top-2 offense; 300+ carries. Allen vultures some scores and Vegas set his catch line at just 30.5 — half-PPR softens that.",["bell","floor","reg"]],
["CeeDee Lamb","WR","DAL",9.7,"buy",2,1,"3 TDs on 6.6 expected, Pickens now drawing coverage, and the best Weeks 15-17 slate in football. Everything points up.",["bnc","ceil"]],
["Derrick Henry","RB","BAL",17.1,"solid",2,2,"Still the bellcow at 32 (71 goal-line carries the last two years). New OC and a shakier line make the mild discount fair.",["bell","age","floor"]],
["Saquon Barkley","RB","PHI",13.8,"solid",3,2,"Elite O-line, true workhorse. The one knock: Philly has the league's worst fantasy-playoff schedule.",["bell","floor"]],
["Kenneth Walker III","RB","KC",14.4,"buy",3,2,"Super Bowl MVP, paid record FA money to be Mahomes' bellcow, camp reports rave about his screen usage. Market still prices the old boring KC backfield.",["bell","ceil"]],
["Chase Brown","RB","CIN",14.8,"solid",3,2,"Lead back in a top-4 Vegas offense. His ADP jumped 5+ spots this summer — the market caught on.",["bell","floor"]],
["A.J. Brown","WR","NE",19.0,"buy",3,2,"Traded to the #2 scoring offense with Drake Maye (led NFL in comp% + Y/A). Projected 130 targets. Alpha again.",["ceil"]],
["Drake London","WR","ATL",21.4,"solid",3,2,"28%+ target share in three of four seasons; 14.0 PPG when healthy. Quiet, elite floor.",["floor"]],
["Ashton Jeanty","RB","LV",12.0,"risk",3,3,"Volume monster (top-15 as an inefficient rookie) with a bigger pass role coming. But Vegas rates the Raiders the NFL's worst offense. Fine at 15-18; a reach at 10-12.",["bell","y2","bb"]],
["Brock Bowers","TE","LV",19.9,"solid",3,1,"The TE1. 103-catch pace across two years, 150-target path. Take him here or punt the position.",["floor","ceil"]],
["Omarion Hampton","RB","LAC",16.5,"solid",3,3,"Lead back with Mike McDaniel now scheming the offense. Ascending situation the market slightly undersells.",["bell","y2","brk"]],
["George Pickens","WR","DAL",23.4,"buy",3,2,"137 targets last year, franchise-tagged, and the Cowboys are THE playoff-week stack (77.6 implied pts, Wks 15-17).",["ceil"]],
["Nico Collins","WR","HOU",23.1,"solid",3,2,"True alpha share — trapped behind a bottom-3 O-line. Fine at this price, don't take him earlier.",["floor"]],
["Malik Nabers","WR","NYG",23.7,"risk",3,2,"ACL + second scar-tissue surgery; five ESPN analysts said bust. But camp flipped positive the last two weeks. Upside WR2 pricing a WR1 ceiling — your risk call.",["rec","ceil","bb"]],
["De'Von Achane","RB","MIA",17.2,"avoid",3,3,"Most injury-prone RB per the models, McDaniel gone, Waddle traded, QB mess, bottom-4 Vegas offense. The clearest early-round fade this year.",["bell","inj","bb"]],
["DeVonta Smith","WR","PHI",27.9,"buy",4,2,"A.J. Brown's exit makes him the unquestioned alpha for the first time. The consensus 'this year's JSN' candidate.",["brk","floor"]],
["Breece Hall","RB","NYJ",28.4,"buy",4,3,"Jets paid him $45M to stay and Geno Smith is a real QB upgrade. Buy the bad-offense discount.",["bell","bnc"]],
["Chris Olave","WR","NO",29.8,"solid",4,2,"20.2 PPG and 9.9 targets/game after landing in New Orleans. Thin room (Tyson hurt) = volume locked in.",["floor"]],
["Emeka Egbuka","WR","TB",32.3,"buy",4,2,"Evans gone, and new OC Zac Robinson moves him all over the formation — the same trick that unlocked Drake London. Breakout consensus.",["y2","brk","ceil"]],
["Rashee Rice","WR","KC",26.8,"risk",4,2,"Mahomes' WR1, no new suspension expected — but one healthy season in three and May knee surgery. WR1 price, WR2 risk profile.",["inj","ceil"]],
["Trey McBride","TE","ARI",29.7,"risk",4,1,"TE-record 126 catches — on Vegas's 2nd-worst offense, with usage that must regress and a rookie RB eating touches. Elite, priced for perfection.",["reg","floor"]],
["Kyren Williams","RB","LAR",32.2,"buy",4,3,"RB7/RB7/RB9 three straight years, 66% of Rams red-zone work, #1 scoring offense. The Corum fear is your discount.",["bell","floor"]],
["Josh Allen","QB","BUF",36.3,"solid",4,1,"The only QB worth an early pick: top-2 at the position 5 of 6 years, 500+ rush yards five straight, now with DJ Moore. If he slides to Rd 3, sprint.",["floor","ceil"]],
["Zay Flowers","WR","BAL",31.0,"solid",4,3,"Two live stories: TD-starved (bounce coming) vs Henry owns the goal line (capped). Both are fine at pick 31 — just never at a WR12 price.",["bnc","cap"]],
["Ladd McConkey","WR","LAC",34.1,"buy",4,3,"McDaniel's new slot engine behind a healthier line. Classic scheme-tailwind bounce-back.",["brk","bnc"]],
["Jeremiyah Love","RB","ARI",25.5,"risk",4,3,"#3 overall pick; Conner has no return timeline and Love already owns the passing downs. But: fresh high-ankle sprain (Wk 1 in doubt) + bottom-2 offense. Pounce only if the ankle discounts him.",["comm","rk","bb","rec"]],
["Javonte Williams","RB","DAL",35.3,"solid",4,4,"69% opportunity share in a top-7 offense last year. Boring, bankable floor.",["bell","floor","cap"]],
["Tee Higgins","WR","CIN",35.1,"risk",4,3,"12 missed games in 3 years and 11 TDs on 6.5 expected. The talent is real; the price ignores both flags.",["inj","reg"]],
["Tetairoa McMillan","WR","CAR",39.8,"solid",4,3,"122 targets as a rookie, ascending offense. Quietly outscored Egbuka last year — the safer sophomore.",["y2","floor"]],
["Jaylen Waddle","WR","DEN",38.5,"buy",4,3,"Traded to the best O-line in football, out of Miami's mess, projected 20-25% share. Watch the minor camp leg issue.",["bnc","ceil"]],
["Garrett Wilson","WR","NYJ",39.3,"solid",4,3,"30% target share when healthy and Geno helps — but the Jets added two 1st-round pass-catchers. Jets tax applies.",["floor"]],
["Cam Skattebo","RB","NYG",43.6,"solid",4,4,"Fully recovered (ankle), leading the backfield, and John Harbaugh wants to pound the rock. Goal-line hammer.",["bell","y2","rec"]],
["Colston Loveland","TE","CHI",43.9,"buy",4,2,"'Unguardable' in camp; TE2 in fantasy over the last 10 weeks of 2025; now the centerpiece of Ben Johnson's play-action game. Top-2 upside, TE3 price.",["y2","brk","ceil"]],
["Terry McLaurin","WR","WAS",47.1,"solid",4,3,"2025 was a holdout mirage — 3 games with a healthy Daniels. Bounce-back projected; Diggs takes a slice of the pie.",["bnc"]],
["Travis Etienne Jr.","RB","NO",42.4,"solid",4,4,"Clear lead back in New Orleans. Kamara still lurks on passing downs; the offense is bottom-10.",["comm","floor","cap"]],
["Luther Burden III","WR","CHI",45.8,"risk",4,3,"The 'next Amon-Ra' role in Ben Johnson's slot — but the Aug 8 groin puts Week 1 in doubt. Take the discount, don't pay sticker.",["y2","rec","bb"]],
["D'Andre Swift","RB","CHI",47.6,"solid",4,4,"Ben Johnson's lead back in a rising offense. ADP climbing for a reason.",["comm","floor","cap"]],
["David Montgomery","RB","HOU",47.3,"solid",4,4,"Traded to Houston for the lead role (Mixon-style usage projected). Bottom-3 O-line is the cap.",["comm","floor","cap"]],
["Josh Jacobs","RB","GB",41.4,"avoid",4,4,"Open felony case (NFL reviewing — a suspension could land mid-season with no warning) plus a groin that's kept him out of camp. At Rd 3-4 cost, a landmine.",["bell","susp","inj"]],
["Mike Evans","WR","SF",48.9,"risk",5,3,"Pearsall's out for the year, so the targets are real. But only two WRs since 2015 finished top-25 at 33+, and his game fights Shanahan's YAC scheme. Fair price, capped ceiling.",["age","cap"]],
["Quinshon Judkins","RB","CLE",53.2,"solid",5,4,"'Looked 100%' after the ankle; locked starter with goal-line work. The league-worst O-line is the tax.",["bell","y2","floor","cap"]],
["DJ Moore","WR","BUF",53.3,"buy",5,4,"Vegas's #2 offense, reunited with Joe Brady, priced like a WR27. The market hasn't caught up yet.",["bnc","ceil"]],
["Lamar Jackson","QB","BAL",56.2,"buy",5,2,"The down 2025 was a hamstring, not decline. Top-2 QB upside at a round-5 price — the best QB value on the board.",["ceil","bnc"]],
["Jameson Williams","WR","DET",51.7,"solid",5,4,"Elite deep threat, but his production halves when LaPorta is healthy (10.2 vs 18.4 PPG). Boom-bust WR3.",["bb"]],
["Bhayshul Tuten","RB","JAX",50.9,"risk",5,4,"Year-2 breakout pick (7 TDs as a rookie) — but beat writers call the Jacksonville backfield genuinely unsettled. Role risk at a rising price.",["comm","y2","bb","brk"]],
["Davante Adams","WR","LAR",52.2,"risk",5,4,"14 TDs drove 38% of his points on a career-low catch rate, and he turns 34 in December. Four outlets flag the same regression.",["age","reg"]],
["Bucky Irving","RB","TB",54.6,"risk",5,4,"Tampa built a real three-man committee (Gainwell, Tucker) and his late-2025 efficiency cratered. Elite line keeps him afloat.",["comm","cap"]],
["Christian Watson","WR","GB",57.5,"solid",5,4,"Green Bay quietly traded away Doubs AND Wicks — someone has to catch the ball. Target-vacuum bet.",["bb"]],
["Rome Odunze","WR","CHI",58.4,"buy",5,4,"On FIVE independent breakout lists — Ben Johnson scheme jump plus a 29% deep-target rate. The consensus sleeper of the summer.",["brk","ceil"]],
["Tyler Warren","TE","IND",62.1,"buy",5,2,"106 targets as a rookie, Pittman traded away, Vegas set his catch line at 74.5 — elite-TE volume at a round-6 price. Take him at cost.",["y2","brk","ceil"]],
["Carnell Tate","WR","TEN",61.7,"solid",5,4,"The safest rookie: instant WR1, elite capital, zero-drop college profile. Bottom-tier offense caps the ceiling.",["rk","floor","cap"]],
["TreVeyon Henderson","RB","NE",57.4,"risk",5,4,"Explosive (top-10 RB down the 2025 stretch) but Stevenson outsnapped him in 15 of 18 games. Price assumes a takeover that isn't confirmed.",["comm","y2","bb","ceil"]],
["Jadarian Price","RB","SEA",61.9,"risk",5,4,"'Prime Dalvin Cook' camp comps; Walker gone, Charbonnet on PUP. He's just back from a month-long leg injury — runway huge, ramp-up real.",["comm","rk","bb","ceil"]],
["Brian Thomas Jr.","WR","JAX",64.0,"solid",5,4,"2025's headline bust — mostly QB chaos. Still the Jaguars' alpha under Coen; decent bounce-back odds at a two-round discount.",["bnc","bb"]],
["Parker Washington","WR","JAX",58.7,"solid",5,4,"Three-list consensus breakout: led JAX in deep-target grade and the market can't decide if he or Thomas is the alpha. Both are startable.",["brk","bb"]],
["Drake Maye","QB","NE",67.1,"buy",5,2,"QB2 overall last year, now throwing to A.J. Brown. If you miss Allen/Lamar, he's the pick.",["ceil"]],
["Joe Burrow","QB","CIN",68.4,"solid",5,2,"Vegas favorite to lead the NFL in passing yards AND TDs. The best stack partner alive (Chase, Higgins).",["floor","ceil"]],
["Jayden Daniels","QB","WAS",69.6,"solid",5,2,"Rushing floor + a real WR duo now (McLaurin, Diggs). New play-caller is the only wrinkle.",["ceil"]],
["Marvin Harrison Jr.","WR","ARI",67.1,"risk",5,3,"The talent is not the question. Vegas's bottom-2 offense, Brissett/Minshew at QB, and the hardest schedule in football are.",["bb"]],
["Jaylen Warren","RB","PIT",70.4,"solid",5,4,"Leads the touches in a run-first McCarthy offense — but Dowdle likely steals the goal line.",["comm","cap"]],
["Rhamondre Stevenson","RB","NE",71.1,"solid",5,4,"The volume half of New England's committee, in the #2 scoring offense. Unsexy RB3 with RB2 weeks.",["comm","floor","cap"]],
["Quentin Johnston","WR","LAC",74.7,"solid",5,4,"ADP up 31 spots this summer — McDaniel's scheme lifts the whole passing game. Momentum play.",["bb"]],
["DK Metcalf","WR","PIT",75.8,"risk",5,4,"Rodgers' quick-release offense mutes the deep ball, and Pittman was added. Name-brand price, WR3 role.",["cap"]],
["Jalen Hurts","QB","PHI",72.8,"solid",5,3,"The rushing TDs always come. Note: the league's toughest Weeks 15-17 slate.",["floor"]],
["Caleb Williams","QB","CHI",73.2,"buy",5,3,"QB5 last year, and now Ben Johnson — the league's best play-designer — arrives. Sneaky top-3 upside.",["ceil","brk"]],
["Tony Pollard","RB","TEN",76.7,"solid",5,4,"Boring volume on a bad team; a foot issue popped up mid-August — worth a status check on draft day.",["bell","floor","cap"]],
["Tucker Kraft","TE","GB",78.2,"solid",5,3,"ACL rehab ahead of schedule ('looks spectacular'). His TD rate will cool, but the thinned-out GB target tree helps.",["rec","reg"]],
["Jayden Reed","WR","GB",79.6,"solid",5,4,"Doubs and Wicks are gone; Reed's slot role is the passing game's stable center.",["bb"]],
["Justin Herbert","QB","LAC",83.7,"buy",5,3,"McDaniel is explicitly speeding up his release behind a healthier line. The market prices last year's sacks, not this year's scheme.",["ceil"]],
["Dak Prescott","QB","DAL",80.8,"solid",5,3,"Led the NFL with 600 attempts; dome-heavy playoff slate. The QB half of the best playoff stack.",["floor"]],
["Josh Downs","WR","IND",81.8,"buy",5,4,"Projection models put him ~40 picks above this price as the Colts' top target-earner. Groin is worth a check on draft day.",["brk"]],
["Courtland Sutton","WR","DEN",83.5,"solid",5,4,"Steady red-zone role in a rising offense — though Waddle's arrival caps the target share.",["floor","cap"]],
["Rico Dowdle","RB","PIT",85.5,"solid",5,5,"The goal-line half of Pittsburgh's committee. TD-dependent flex.",["comm","cap"]],
["Trevor Lawrence","QB","JAX",86.5,"solid",5,4,"Resurgent under Coen (QB4 last year). Fine QB1 if you punted.",["floor"]],
["Chris Godwin Jr.","WR","TB",87.5,"solid",5,5,"Re-signed, reliable slot floor in a good offense. The ceiling belongs to Egbuka now.",["floor","cap"]],
["Sam LaPorta","TE","DET",88.5,"solid",5,2,"Top-5 TE in a top-3 offense, priced round 8 because 2025 was 'only' good. Easy value if you punted TE.",["floor"]],
["Blake Corum","RB","LAR",89.5,"solid",6,5,"The #1 handcuff in fantasy — paced 900+ rushing yards over the last 10 games of 2025. Standalone flex value, league-winner if Kyren misses.",["comm","cuff","ceil"]],
["RJ Harvey","RB","DEN",88.0,"risk",6,5,"Talented, but the TD luck (+3.9) regresses and Denver's room is four deep. Scheme's great; role isn't.",["comm","y2","reg","bb"]],
["Jordan Addison","WR","MIN",90.1,"solid",6,5,"TD-unlucky in 2025 and Kyler raises the whole boat. Solid WR4 with WR2 stretches.",["bnc"]],
["Jonathon Brooks","RB","CAR",78.8,"risk",6,5,"ADP up FIFTY spots on health buzz — for 9 career carries, two ACL tears, and an entrenched starter ahead. Let someone else chase it.",["comm","inj","rec"]],
["Chuba Hubbard","RB","CAR",95.1,"risk",6,5,"The entrenched starter in question — but he's week-to-week with a hamstring right now. Check status.",["bell","inj"]],
["J.K. Dobbins","RB","DEN",96.4,"risk",6,5,"Has never played a full season, and there's already a new camp hamstring issue. Great line, fragile bet.",["comm","inj"]],
["Patrick Mahomes","QB","KC",97.3,"risk",6,4,"Cleared from the ACL/LCL, but the rushing floor that made him top-5 is compromised. QB2 with a brand-name price.",["rec","cap"]],
["Kyle Monangai","RB","CHI",98.6,"risk",6,5,"Ben Johnson's between-the-tackles TD sneak — but he hyperextended a knee in mid-August and Week 1 is now questionable.",["comm","y2","cap","rec"]],
["Michael Pittman Jr.","WR","PIT",99.3,"solid",6,5,"Traded to Pittsburgh; steady possession role in a run-first offense.",["floor","cap"]],
["Stefon Diggs","WR","WAS",100.9,"buy",6,5,"Signed Aug 5 — instantly the clear #2 opposite McLaurin with Daniels throwing. ADP hasn't caught up to a two-week-old reality.",["bnc"]],
["Jordan Mason","RB","MIN",103.1,"buy",6,5,"Quietly winning Minnesota's backfield from an aging Aaron Jones (13.5 PPG as a 2025 fill-in). A starting RB in round 8-9.",["comm","brk","floor"]],
["Jaxson Dart","QB","NYG",101.6,"solid",6,4,"17.6 PPG as a rookie; adds Likely and (eventually) a healthy Nabers. Fine late QB1.",["y2","ceil"]],
["Brock Purdy","QB","SF",102.0,"buy",6,4,"20.8 PPG when healthy — top-3 rate — and nobody drafts him. The efficient-market violation at QB.",["floor"]],
["Xavier Worthy","WR","KC",105.1,"buy",6,5,"Models say top-90 value; Mahomes is back and Rice's screens are getting redistributed. Speed lottery ticket with real volume.",["ceil","bb"]],
["Matthew Golden","WR","GB",104.9,"buy",6,5,"Model-projected ~40 picks above price in a receiver room that just lost two starters.",["y2","brk"]],
["Bo Nix","QB","DEN",107.0,"buy",6,4,"QB7 two straight years, best O-line in football, they traded a 1st for Waddle — and he's priced QB14. Buy.",["floor"]],
["Jacory Croskey-Merritt","RB","WAS",107.6,"buy",6,5,"126 vacated Washington carries and the projection models' favorite late RB (+22 vs ADP).",["comm","brk"]],
["Kyle Pitts Sr.","TE","ATL",102.5,"risk",6,3,"19.0 PPG without London on the field, 9.6 with him. London is healthy — price him accordingly.",["bb","cap"]],
["Harold Fannin Jr.","TE","CLE",102.4,"avoid",6,4,"Small-sample 2025 magic; TE-friendly coach gone, rookie WRs added, QB chaos. Most overdrafted TE on the board.",["y2","reg"]],
["Matthew Stafford","QB","LAR",108.8,"risk",6,4,"Reigning MVP, 46 TDs at 38 — base rates say ~30 this year. Fine QB2; on ESPN his ADP runs two rounds hotter, don't chase it.",["age","reg"]],
["Jared Goff","QB","DET",110.7,"solid",6,4,"Four straight 4,000-yard years; the Amon-Ra stack partner. Steady late QB1.",["floor","cap"]],
["Kyler Murray","QB","MIN",113.5,"buy",6,4,"Named the Vikings' starter Aug 11 with Jefferson, Addison and Hockenson attached — still priced QB18. The late-round QB steal of 2026.",["bnc","ceil","inj"]],
["George Kittle","TE","SF",113.8,"risk",6,3,"Racing an aggressive Achilles timeline to Week 1. If the discount holds, low-end TE1 with spike weeks; any setback = Weeks 2-3.",["rec","age"]],
["Rachaad White","RB","WAS",114.4,"solid",6,5,"Leads Washington's murky backfield for now — Croskey-Merritt and rookie Kaytron Allen are coming.",["comm","cap"]],
["Wan'Dale Robinson","WR","TEN",111.6,"solid",6,5,"140 targets in 2025 (with NYG); now Tennessee's slot volume piece. PPR-shaped, still fine in half.",["floor","cap"]],
["Jakobi Meyers","WR","JAX",115.4,"solid",6,5,"Dependable target-earner in a top-6 scoring offense from 2025.",["floor","cap"]],
["Makai Lemon","WR","PHI",82.5,"risk",6,6,"Round-1 pick positioned as Philly's WR2 — but a camp hamstring means a ramp-up. Underdog best-ball ADP (83) way overheats his redraft value; treat as a rd-12 dart.",["rk","rec","bb"]],
["Jordan Love","QB","GB",116.3,"solid",6,5,"Volatile but the receiver-room churn hurts. Matchup-play QB2.",["bb"]],
["Kenneth Gainwell","RB","TB",109.5,"risk",6,5,"The passing-down slice of a three-way committee; Mayfield red-zone stack appeal only.",["comm","cap"]],
["Isaiah Likely","TE","NYG",125.7,"buy",6,4,"Giants paid him $40M and he's been Dart's clear top read while Nabers ramps up. The best TE-punt target.",["brk"]],
["Tyler Shough","QB","NO",125.5,"solid",6,5,"18+ PPG down his rookie stretch; added Etienne and (when healthy) Tyson. Sneaky QB2 with starter upside.",["y2","brk"]],
["Baker Mayfield","QB","TB",121.8,"solid",6,5,"Elite line, new McVay-tree OC, Egbuka stack. Reliable late QB1-by-committee.",["floor"]],
["Jayden Higgins","WR","HOU",121.2,"solid",6,5,"Kirk's departure opens the Houston WR2 job; big frame, quiet riser.",["y2","brk"]],
["Romeo Doubs","WR","NE",118.3,"solid",6,5,"Traded into the #2 scoring offense; sneaky depth with Maye throwing.",["cap"]],
["Michael Wilson","WR","ARI",91.8,"solid",6,5,"2025's waiver MVP stretch was real, but the Cardinals tax (bottom-2 offense, QB mess) applies to him too.",["bb"]],
["Dalton Kincaid","TE","BUF",123.3,"risk",6,4,"Best per-route TE in football on a tiny snap share. The bet is 'more usage' — experts say the market already over-bet it.",["bb","reg","inj"]],
["Khalil Shakir","WR","BUF",130.9,"buy",7,5,"Models put him ~57 picks above this price. Allen's most-trusted underneath target in a 26-point offense.",["floor"]],
["De'Zhaun Stribling","WR","SF",126.4,"buy",7,5,"High-stakes ADP jumped 64 spots in a week — SF's WR room is decimated and Purdy trusts him. The sharp money's rookie dart.",["rk","brk","bb"]],
["Denzel Boston","WR","CLE",140.3,"buy",7,5,"The camp riser of the summer: first-team already, 'best Browns WR in camp.' Basically free.",["rk","brk"]],
["Jake Ferguson","TE","DAL",134.0,"solid",7,4,"Dak's red-zone TE in the best playoff-schedule offense. Fine punt target.",["cap"]],
["Mark Andrews","TE","BAL",130.8,"risk",7,4,"Likely's exit helps, but experts have him among the most overdrafted TEs. Late only.",["age","cap"]],
["Zach Charbonnet","RB","SEA",159.4,"buy",7,6,"'The most proven handcuff in football' — Seattle's lead back whenever the ACL rehab completes. Elite stash.",["comm","cuff","rec"]],
["MarShawn Lloyd","RB","GB",160.5,"buy",7,6,"The Jacobs contingency plan. High-stakes sharps moved him up 19 spots in a week — they're pricing the suspension risk.",["comm","cuff","bb"]],
["Tyler Allgeier","RB","ARI",148.1,"buy",7,6,"If Love's high-ankle sprain lingers into September, Allgeier opens as Arizona's starter. Free insurance either way.",["comm","cuff"]],
["Alvin Kamara","RB","NO",161.8,"solid",7,6,"Restructured to stay; the passing-down floor role in New Orleans. Half-PPR trims his edge.",["comm","age","cap"]],
["Woody Marks","RB","HOU",141.6,"buy",7,6,"Scored 5 TDs on 7.8 expected as a rookie — positive regression — and he's the Montgomery insurance. Deep-league gold.",["comm","y2","bnc"]],
["Travis Hunter","WR","JAX",148.9,"solid",7,5,"Full-time WR2 now in Coen's offense. The two-way novelty is gone; the talent isn't.",["y2","ceil"]],
["Rashid Shaheed","WR","SEA",133.8,"solid",7,6,"Seattle's field-stretcher; JSN's gravity leaves him single coverage.",["bb"]],
["Deebo Samuel Sr.","WR","SF",128.0,"risk",7,6,"Four straight years: hot start, then injuries. The pattern is the profile.",["inj","age"]],
["Dallas Goedert","TE","PHI",135.1,"avoid",7,5,"11 TDs on 5.1 expected — a career-year fluke at 31. Projections say TE20.",["age","reg"]],
["Malik Willis","QB","MIA",134.8,"risk",7,5,"If he wins the job: a 58-rush-yards-per-game floor. But Miami's QB battle is genuinely unresolved. Watch, don't reach.",["bb"]],
["Sam Darnold","QB","SEA",142.2,"solid",7,5,"Super Bowl-winning continuity; fine streamer with a champion's schedule.",["floor"]],
["Daniel Jones","QB","IND",146.8,"solid",7,5,"The rare clean Achilles recovery — no camp limitations, ADP rising. Stabilizes the whole Colts offense.",["rec","floor"]],
["C.J. Stroud","QB","HOU",145.5,"solid",7,5,"Improved AFC South schedule; O-line still the anchor dragging him down.",["cap"]],
["T.J. Hockenson","TE","MIN",170.3,"solid",7,4,"Kyler's arrival lifts every Viking. Free TE with TE1-week upside.",["bnc"]],
["Oronde Gadsden II","TE","LAC",167.5,"solid",7,4,"McDaniel schemes touches to TEs in space. Deep-league punt with a real role.",["y2","brk"]],
["Travis Kelce","TE","KC",122.7,"avoid",7,4,"Turns 37, two straight years of decline, value hostage to Mahomes' knee. The name costs three rounds more than the player.",["age","reg"]],
["Isiah Pacheco","RB","DET",168.9,"solid",7,6,"Signed with Detroit — the direct Gibbs handcuff in the league's best RB environment.",["comm","cuff"]],
["Tyrone Tracy Jr.","RB","NYG",136.6,"solid",7,6,"The passing-down complement (and insurance) to Skattebo.",["comm","cuff"]],
["Tank Bigsby","RB","PHI",151.1,"solid",7,6,"Now in Philadelphia (recent move) — the direct Saquon handcuff behind the league's best line. Zero-RB stash.",["comm","cuff","bb"]],
["Tyjae Spears","RB","TEN",157.9,"solid",7,6,"Pollard insurance with standalone passing-down work.",["comm","cuff"]],
["Keaton Mitchell","RB","LAC",130.8,"solid",7,6,"Explosive space player McDaniel will scheme touches for. Boom-or-bench.",["comm","bb"]],
["Jalen Coker","WR","CAR",129.4,"solid",7,6,"FantasyPros 'draft' flag — 100+ target profile if the McMillan-opposite role sticks.",["brk"]],
["Dontayvion Wicks","WR","PHI",166.3,"solid",7,6,"Traded to Philly's suddenly thin room; cheap route to WR3 snaps.",["bb"]],
["Zachariah Branch","WR","ATL",184.4,"buy",7,6,"First-team reps and a 50-yard TD in his first padded practice. Path to Falcons WR2 for free.",["rk","brk"]],
["Jordyn Tyson","WR","NO",69.1,"risk",7,6,"Elite rookie profile, clear #2 role — and a hamstring that shelves him until ~October. Ignore the stale best-ball ADP; he's a rd-14 stash or a waiver add.",["rk","rec"]],
["Omar Cooper Jr.","WR","NYJ",155.5,"solid",7,6,"Round-1 capital behind Garrett Wilson; 'the risk is all baked in' at this price.",["rk","bb"]],
["Keon Coleman","WR","BUF",210.0,"solid",7,6,"Fighting for the WR3 job in Vegas's #2 offense. Last-round flier.",["bb"]],
["Cooper Kupp","WR","SEA",211.1,"solid",7,6,"Still in Seattle, still crafty — deep-league depth only at this stage.",["age","cap"]],
["Kenyon Sadiq","TE","NYJ",178.5,"risk",7,5,"Elite rookie TE athleticism (4.39 forty), but a hernia setback and a crowded low-scoring passing game. Dynasty > redraft.",["rk","rec"]],
["Kaytron Allen","RB","WAS",211.5,"buy",7,6,"Penn State's all-time leading rusher, graded more talented than Washington's incumbents. Free last-round swing.",["comm","rk","cuff"]],
["Aaron Jones Sr.","RB","MIN",126.3,"risk",7,5,"2,000+ career touches and Mason is visibly taking over. The fade side of the Minnesota backfield.",["comm","age","cap"]],
["Aaron Rodgers","QB","PIT",180.4,"solid",7,5,"One last run-first, play-action season. Streamer at best — but a fine bye-week QB.",["age","cap"]]
];

export const OT: Record<number, [string, string]> = {
  1: ["The Big Three", "picks 1–3"],
  2: ["Elite Anchors", "round 1"],
  3: ["Rounds 2–3 Pillars", "the last bellcows & alpha WRs"],
  4: ["Rounds 3–5", "last of the locks"],
  5: ["Rounds 5–8", "the value zone"],
  6: ["Rounds 8–11", "role bets & late QBs"],
  7: ["Rounds 12–15", "darts, cuffs & stashes"],
};

export const PT: Record<string, Record<number, [string, string]>> = {
  QB: { 1: ["The Exception", "Allen — the only early QB"], 2: ["Difference-Makers", "rounds 5–7"], 3: ["Set-and-Forget", "rounds 6–8"], 4: ["The Value Shelf", "rounds 8–11 — wait & win"], 5: ["Streamers", "rounds 12+ / waivers"] },
  RB: { 1: ["The 1.01 Debate", "picks 1–2"], 2: ["True Bellcows", "rounds 1–2"], 3: ["High-End RB2s", "rounds 2–3 — talent or situation, pick one"], 4: ["The Dead Zone", "rounds 4–7 — tread carefully"], 5: ["Role Bets", "rounds 7–10"], 6: ["Handcuffs & Darts", "rounds 11+"] },
  WR: { 1: ["Alphas", "rounds 1–2"], 2: ["WR1s With a Catch", "rounds 2–3"], 3: ["Strong WR2s", "rounds 3–5"], 4: ["Flex With Upside", "rounds 5–8"], 5: ["Bench Value", "rounds 8–12 — the model darlings"], 6: ["Darts & Stashes", "rounds 13+"] },
  TE: { 1: ["Pay Up or Move On", "round 2–3"], 2: ["The Smart Middle", "rounds 4–8"], 3: ["Talent & Health Gambles", "rounds 8–10"], 4: ["Punt Targets", "rounds 10+"], 5: ["Streamers", "late / waivers"] },
};

export const VLBL: Record<Verdict, string> = { buy: "VALUE", solid: "SOLID", risk: "RISKY", avoid: "AVOID" };

export const TAGS: Record<string, [string, string]> = {
  bell: ["Bellcow", "The backfield is his — carries AND catches"],
  comm: ["Committee", "Splits the backfield — capped weekly role"],
  ceil: ["High ceiling", "Legit league-winning upside"],
  floor: ["High floor", "Safe weekly points"],
  cap: ["Low ceiling", "Useful, but rarely wins you a week"],
  bb: ["Boom-bust", "Big weeks and zero weeks"],
  inj: ["Injury-prone", "Multi-year pattern of missed games"],
  rec: ["Returning", "Coming back from a major injury"],
  age: ["Age risk", "Wrong side of the aging curve"],
  reg: ["TD regression", "Scored more TDs than his chances predict — expect fewer"],
  bnc: ["Bounce-back", "Unlucky or broken 2025 — expect more"],
  brk: ["Breakout bet", "Role or situation just opened up"],
  rk: ["Rookie", "First NFL season"],
  y2: ["Year 2", "Second-season leap candidate"],
  cuff: ["Handcuff", "Backup who inherits a big role on injury"],
  susp: ["Suspension risk", "League discipline pending"],
};

export const TAGCLASS: Record<string, string> = {
  inj: "warn", susp: "warn", reg: "warn", age: "warn",
  ceil: "good", brk: "good", bnc: "good", floor: "good", bell: "good",
};

export const BYE: Record<string, number> = {
  KC: 5, CAR: 5, CIN: 6, DET: 6, MIA: 6, MIN: 6, BUF: 7, JAX: 7, LAC: 7, WAS: 7,
  HOU: 8, NO: 8, NYG: 8, SF: 8, PIT: 9, TEN: 9, CHI: 10, DEN: 10, PHI: 10, TB: 10,
  ATL: 11, CLE: 11, GB: 11, LAR: 11, NE: 11, SEA: 11, BAL: 13, IND: 13, LV: 13, NYJ: 13,
  ARI: 14, DAL: 14,
};

export const CUFFS: Record<string, string> = {
  "Kyren Williams": "Blake Corum",
  "Jahmyr Gibbs": "Isiah Pacheco",
  "Saquon Barkley": "Tank Bigsby",
  "Jeremiyah Love": "Tyler Allgeier",
  "Josh Jacobs": "MarShawn Lloyd",
  "Cam Skattebo": "Tyrone Tracy Jr.",
  "Tony Pollard": "Tyjae Spears",
};

/** [team, implied PPG, weeks 15–17 implied total] */
export const VEGAS: [string, number, number][] = [
  ["Rams", 26.7, 78.8], ["Bills", 26.1, 79.0], ["Lions", 26.1, 75.0], ["Bengals", 26.0, 79.0],
  ["Ravens", 25.9, 75.8], ["Cowboys", 25.7, 77.6], ["49ers", 25.0, 67.8], ["Packers", 24.8, 73.5],
  ["Seahawks", 24.8, 69.5], ["Bears", 24.6, 74.0], ["Chiefs", 24.1, 70.8], ["Chargers", 23.8, 74.8],
  ["Patriots", 23.8, 67.5], ["Eagles", 23.8, 64.5], ["Jaguars", 23.5, 70.6], ["Commanders", 23.5, 69.5],
  ["Colts", 23.4, 73.0], ["Buccaneers", 23.3, 70.0], ["Texans", 22.5, 60.8], ["Vikings", 22.4, 68.5],
  ["Broncos", 22.3, 65.5], ["Giants", 22.1, 67.5], ["Saints", 21.5, 67.5], ["Steelers", 21.4, 66.5],
  ["Falcons", 21.2, 66.5], ["Panthers", 20.8, 60.0], ["Titans", 20.6, 64.0], ["Raiders", 19.2, 62.5],
  ["Dolphins", 19.0, 56.8], ["Browns", 18.7, 55.3], ["Jets", 18.5, 56.5], ["Cardinals", 18.4, 60.0],
];
