// Regenerates src/teams-logos.ts: inline data URIs for all 32 NFL team logos
// (80px PNGs via ESPN's combiner). Run: node scripts/fetch-logos.mjs
import { writeFileSync } from "node:fs";

const CODES = {
  ARI: "ari", ATL: "atl", BAL: "bal", BUF: "buf", CAR: "car", CHI: "chi", CIN: "cin", CLE: "cle",
  DAL: "dal", DEN: "den", DET: "det", GB: "gb", HOU: "hou", IND: "ind", JAX: "jax", KC: "kc",
  LV: "lv", LAC: "lac", LAR: "lar", MIA: "mia", MIN: "min", NE: "ne", NO: "no", NYG: "nyg",
  NYJ: "nyj", PHI: "phi", PIT: "pit", SEA: "sea", SF: "sf", TB: "tb", TEN: "ten", WAS: "wsh",
};

const out = {};
for (const [abbr, code] of Object.entries(CODES)) {
  const url = `https://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/${code}.png&h=80&w=80`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${abbr}: HTTP ${res.status}`);
  const buf = Buffer.from(await res.arrayBuffer());
  out[abbr] = `data:image/png;base64,${buf.toString("base64")}`;
  console.log(`${abbr} ${(buf.length / 1024).toFixed(1)}KB`);
}

const ts =
  "/** Generated by scripts/fetch-logos.mjs — inline 80px NFL team logos. */\n" +
  "export const TEAM_LOGOS: Record<string, string> = {\n" +
  Object.entries(out).map(([k, v]) => `  ${k}: "${v}",`).join("\n") +
  "\n};\n";
writeFileSync(new URL("../src/teams-logos.ts", import.meta.url), ts);
console.log("wrote src/teams-logos.ts");
