// Regenerates src/sleeper.ts: live injury status + 24h trending add/drop heat for every
// board player, from Sleeper's free read-only API (docs.sleeper.com — no token; their
// guidance is simply to stay under 1000 calls/min; this script makes 3).
// Run: node scripts/fetch-sleeper.mjs
import { readFileSync, writeFileSync } from "node:fs";

const norm = (s) =>
  s
    .toLowerCase()
    .replace(/[.'-]/g, " ")
    .replace(/\b(jr|sr|ii|iii|iv|v)\b/g, "")
    .replace(/\s+/g, " ")
    .trim();

const dataTs = readFileSync(new URL("../src/data.ts", import.meta.url), "utf8");
const boardNames = [...dataTs.matchAll(/^\["((?:[^"\\]|\\.)*)",/gm)].map((m) => m[1]);
console.log(`board names: ${boardNames.length}`);

const players = await (await fetch("https://api.sleeper.app/v1/players/nfl")).json();
const trendAdd = await (await fetch("https://api.sleeper.app/v1/players/nfl/trending/add?lookback_hours=24&limit=200")).json();
const trendDrop = await (await fetch("https://api.sleeper.app/v1/players/nfl/trending/drop?lookback_hours=24&limit=200")).json();
// Sleeper's REAL average draft position, half-PPR flavour — the pick our league actually
// drafts at. Their projections feed carries an adp_* per format; adp_half_ppr matches our
// scoring. 999 is Sleeper's "no data" sentinel.
const projections = await (
  await fetch("https://api.sleeper.com/projections/nfl/2026?season_type=regular")
).json();
const adpByName = new Map();
for (const row of projections) {
  const a = row?.stats?.adp_half_ppr;
  if (typeof a !== "number" || a >= 999) continue;
  const pl = row.player ?? {};
  const nm = pl.full_name || [pl.first_name, pl.last_name].filter(Boolean).join(" ");
  if (!nm) continue;
  const key = norm(nm);
  if (!adpByName.has(key) || a < adpByName.get(key)) adpByName.set(key, a);
}

const byName = new Map();
for (const [pid, p] of Object.entries(players)) {
  if (!p || typeof p !== "object" || !p.full_name) continue;
  if (!["QB", "RB", "WR", "TE"].includes(p.position)) continue;
  const key = norm(p.full_name);
  // prefer active players on a team when names collide
  if (!byName.has(key) || (p.team && p.status === "Active")) byName.set(key, { pid, p });
}
const addCount = Object.fromEntries(trendAdd.map((t) => [t.player_id, t.count]));
const dropCount = Object.fromEntries(trendDrop.map((t) => [t.player_id, t.count]));

const out = {};
let injN = 0;
let trendN = 0;
let adpN = 0;
for (const name of boardNames) {
  const hit = byName.get(norm(name));
  if (!hit) continue;
  const { pid, p } = hit;
  const entry = {};
  const inj = p.injury_status || (["Injured Reserve", "PUP", "Suspended"].includes(p.status) ? p.status : "");
  if (inj) {
    const short = { Questionable: "Q", Doubtful: "D", Out: "O", "Injured Reserve": "IR", PUP: "PUP", Sus: "SUS", Suspended: "SUS", DNR: "O", NA: "NA" }[inj] ?? inj;
    entry.inj = short;
    injN++;
  }
  const adds = addCount[pid] ?? 0;
  const drops = dropCount[pid] ?? 0;
  if (adds >= 1000 || drops >= 1000) {
    entry.trend = adds >= drops ? adds : -drops;
    trendN++;
  }
  // Sleeper's real half-PPR ADP — the pick this player actually goes at on Sleeper.
  const adp = adpByName.get(norm(name));
  if (typeof adp === "number") {
    entry.adp = Math.round(adp * 10) / 10;
    adpN++;
  }
  // Sleeper's board-sort rank. NOTE: this is superflex-flavoured — it places QBs ~37 picks
  // earlier than a 1-QB league does — so it is kept for display only, never for pricing.
  if (typeof p.search_rank === "number" && p.search_rank <= 400) entry.rk = p.search_rank;
  if (Object.keys(entry).length) out[name] = entry;
}

const stamp = new Date().toISOString().slice(0, 16).replace("T", " ");
const ts =
  `/** Generated by scripts/fetch-sleeper.mjs — Sleeper live injury designations, 24h waiver\n` +
  ` *  trending, real half-PPR ADP, and Sleeper's board-sort rank. Refreshed ${stamp} UTC.\n` +
  ` *\n` +
  ` *  adp — Sleeper's REAL average draft position in half-PPR leagues. This is the number the\n` +
  ` *        model prices players with, because it is the pick our league actually drafts at.\n` +
  ` *  rk  — Sleeper's in-app board-sort rank. Superflex-flavoured: it lists QBs roughly 37 picks\n` +
  ` *        earlier than a 1-QB league drafts them, so it is displayed but never priced on. */\n` +
  `export const SLP: Record<string, { inj?: string; trend?: number; rk?: number; adp?: number }> = ${JSON.stringify(out, null, 0)};\n`;
writeFileSync(new URL("../src/sleeper.ts", import.meta.url), ts);
console.log(
  `wrote src/sleeper.ts — ${injN} injury flags, ${trendN} trending, ${adpN} real ADP, ${Object.keys(out).length} entries`,
);
