import assert from 'node:assert/strict';
import {buildSync} from 'esbuild';
import {createRequire} from 'node:module';
import {relativeScoringRates,validRisk} from './scoring-spread.mjs';
assert.deepEqual(relativeScoringRates([0,0,0,0,0,10],0),{boom:null,bust:null},'zero-median scoring has no meaningful relative boom/bust rates');
assert.deepEqual(relativeScoringRates([-1,0,0],-1),{boom:null,bust:null});
assert.deepEqual(relativeScoringRates([0,5,10,15,20],10),{boom:.4,bust:.4},'include exact threshold values for positive medians');
const sparse=[...Array(9).fill(0),10],mean=1,cv=Math.sqrt(sparse.reduce((s,x)=>s+(x-mean)**2,0)/9)/mean;
assert.ok(cv>2);assert.ok(validRisk({cv,pMiss:.22,knownMiss:0}),'legitimate sparse scoring can have CV above two');
assert.ok(validRisk({cv:0,pMiss:0,knownMiss:0}),'constant production has zero CV');
for(const cv of [-1,Infinity,NaN])assert.equal(validRisk({cv,pMiss:.2,knownMiss:0}),false);
for(const pMiss of [-.1,1.1,Infinity,NaN])assert.equal(validRisk({cv:.4,pMiss,knownMiss:0}),false);
for(const knownMiss of [-.1,1.1,Infinity,NaN])assert.equal(validRisk({cv:.4,pMiss:.2,knownMiss}),false);
assert.ok(validRisk({cv:3,pMiss:1,knownMiss:1}));
const compiled=buildSync({stdin:{contents:'export {riskOf} from "./src/lib/risk"; export {CEIL} from "./src/ceilings";',resolveDir:process.cwd()},bundle:true,platform:'node',format:'cjs',write:false}).outputFiles[0].text;
const mod={exports:{}};new Function('exports','module','require',compiled)(mod.exports,mod,createRequire(import.meta.url));
const {riskOf,CEIL}=mod.exports,name='Scoring spread fixture';
CEIL[name]={tdShare:0,touches:0,cv:2.85,p10:0,p90:1.1,boom:null,bust:null,games:14};
const neutral=riskOf(name,'WR','solid');
assert.equal(neutral.flags.some(f=>/median|ceiling|wins a week|disappeared/.test(f)),false,'null rates must not become low-ceiling claims');
CEIL[name]={...CEIL[name],boom:.5,bust:.3};
const measured=riskOf(name,'WR','solid');
assert.equal(measured.cv,neutral.cv);assert.equal(measured.pMiss,neutral.pMiss);assert.equal(measured.knownMiss,neutral.knownMiss);
assert.ok(measured.flags.includes('scored at least 1.5x his own median in 50% of his 2025 games'));
assert.ok(measured.flags.includes('scored at most half his own median in 30% of his 2025 games'));
console.log('PASS: zero-median rates, legitimate large/zero CV, and finite probability bounds');
